// ============================================
// 源来如此 — 内置词库（高中+雅思+GRE+商务+学术+日常+科技），CET4/CET6/TOEFL 由 data/ JSON 动态加载
// ============================================
const WORD_LIBRARIES = {

    senior: {
        name: '高中', emoji: '🏫',
        data: [
            { en: 'abandon', zh: '放弃；抛弃', explain: 'to give up completely' }, { en: 'ability', zh: '能力；才能', explain: 'the power or skill to do sth' }, { en: 'abroad', zh: '到国外', explain: 'in or to a foreign country' }, { en: 'absence', zh: '缺席；不在', explain: 'the state of being away' }, { en: 'absolute', zh: '绝对的；完全的', explain: 'total and complete' }, { en: 'absorb', zh: '吸收；吸引', explain: 'to take in liquid/gas/heat' }, { en: 'abstract', zh: '抽象的；摘要', explain: 'relating to ideas, not physical things' }, { en: 'abundant', zh: '丰富的；充裕的', explain: 'existing in large quantities' }, { en: 'academic', zh: '学术的', explain: 'relating to education and scholarship' }, { en: 'accelerate', zh: '加速；促进', explain: 'to happen or make sth happen faster' }, { en: 'access', zh: '通道；进入；使用权', explain: 'the right or opportunity to use sth' }, { en: 'accommodation', zh: '住宿；膳宿', explain: 'a place to live, work, or stay' }, { en: 'accompany', zh: '陪同；伴随', explain: 'to go somewhere with sb' }, { en: 'accomplish', zh: '完成；实现', explain: 'to succeed in doing sth' }, { en: 'account', zh: '账户；说明', explain: 'an arrangement with a bank' }, { en: 'accurate', zh: '准确的；精确的', explain: 'correct and true in every detail' }, { en: 'accuse', zh: '指责；控告', explain: 'to say sb has done sth wrong' }, { en: 'achieve', zh: '达到；取得', explain: 'to succeed in reaching a goal' }, { en: 'acknowledge', zh: '承认；确认', explain: 'to accept that sth is true' }, { en: 'acquire', zh: '获得；习得', explain: 'to gain sth by your own efforts' }, { en: 'adapt', zh: '适应；改编', explain: 'to change to suit new conditions' }, { en: 'addict', zh: '上瘾者', explain: 'a person unable to stop doing sth' }, { en: 'adequate', zh: '足够的；适当的', explain: 'enough in quantity or good enough in quality' }, { en: 'adjust', zh: '调整；适应', explain: 'to change sth slightly' }, { en: 'administration', zh: '管理；行政', explain: 'the process of managing an organization' }, { en: 'admire', zh: '钦佩；赞赏', explain: 'to respect and like sb/sth' }, { en: 'admit', zh: '承认；准许进入', explain: 'to agree that sth is true' }, { en: 'adopt', zh: '采用；收养', explain: 'to take and use as your own' }, { en: 'advance', zh: '前进；进步', explain: 'to move forward or make progress' }, { en: 'advantage', zh: '优势；有利条件', explain: 'a condition that helps you' }, { en: 'adventure', zh: '冒险；奇遇', explain: 'an exciting or unusual experience' }, { en: 'advertise', zh: '做广告；宣传', explain: 'to tell the public about a product' }, { en: 'advocate', zh: '提倡；拥护者', explain: 'to publicly support an idea' }, { en: 'affair', zh: '事务；事件', explain: 'an event or situation' }, { en: 'affect', zh: '影响；感动', explain: 'to have an influence on sb/sth' }, { en: 'afford', zh: '负担得起；提供', explain: 'to have enough money to pay for' }, { en: 'agenda', zh: '议程', explain: 'a list of items to be discussed' }, { en: 'aggressive', zh: '侵略的；好斗的', explain: 'behaving in an angry, threatening way' }, { en: 'agreement', zh: '协议；同意', explain: 'an arrangement or promise between people' }, { en: 'agriculture', zh: '农业；农学', explain: 'the practice of farming' }, { en: 'allocate', zh: '分配；拨出', explain: 'to give sth officially for a purpose' }, { en: 'alternative', zh: '替代的；选择', explain: 'one of two or more possibilities' }, { en: 'amateur', zh: '业余的；爱好者', explain: 'sb who does sth for pleasure, not as a job' }, { en: 'ambition', zh: '雄心；野心', explain: 'a strong desire for success' }, { en: 'analyze', zh: '分析；解析', explain: 'to examine sth in detail' }, { en: 'ancestor', zh: '祖先；祖宗', explain: 'a person in your family who lived long ago' }, { en: 'ancient', zh: '古代的；古老的', explain: 'belonging to a time long ago' }, { en: 'anniversary', zh: '周年纪念日', explain: 'the date on which sth special happened' }, { en: 'announce', zh: '宣布；通告', explain: 'to tell people about sth officially' }, { en: 'annual', zh: '每年的；年度的', explain: 'happening once every year' }, { en: 'anticipate', zh: '预期；期望', explain: 'to expect that sth will happen' }, { en: 'anxiety', zh: '焦虑；忧虑', explain: 'the state of feeling nervous or worried' }, { en: 'apparent', zh: '显然的；表面上的', explain: 'easy to see or understand' }, { en: 'appeal', zh: '呼吁；吸引；上诉', explain: 'to make a serious request' }, { en: 'appetite', zh: '食欲；胃口', explain: 'a natural desire to satisfy a need' }, { en: 'appliance', zh: '电器；器具', explain: 'a machine designed for a specific use' }, { en: 'application', zh: '应用；申请', explain: 'a formal request for sth' }, { en: 'appoint', zh: '任命；指定', explain: 'to choose sb for a job or position' }, { en: 'appreciate', zh: '欣赏；感激', explain: 'to recognize the value of sb/sth' }, { en: 'approach', zh: '接近；方法', explain: 'to come near to sb/sth' }, { en: 'appropriate', zh: '适当的', explain: 'suitable or right for a situation' }, { en: 'approve', zh: '批准；赞成', explain: 'to officially agree to a plan' }, { en: 'architect', zh: '建筑师', explain: 'a person who designs buildings' }, { en: 'argue', zh: '争论；辩论', explain: 'to speak angrily because you disagree' }, { en: 'arise', zh: '出现；产生', explain: 'to happen as a result of a situation' }, { en: 'arrange', zh: '安排；整理', explain: 'to plan or organize sth' }, { en: 'arrest', zh: '逮捕', explain: 'to take sb to a police station' }, { en: 'article', zh: '文章；物品；冠词', explain: 'a piece of writing in a newspaper' }, { en: 'aspect', zh: '方面；层面', explain: 'one part of a situation or problem' }, { en: 'assemble', zh: '集合；组装', explain: 'to bring people or things together' }, { en: 'assess', zh: '评估；评定', explain: 'to judge the value or quality of sth' }, { en: 'assign', zh: '分配；指派', explain: 'to give sb a particular task' }, { en: 'assist', zh: '帮助；协助', explain: 'to help sb to do sth' }, { en: 'associate', zh: '关联；联系', explain: 'to make a connection between things' }, { en: 'assume', zh: '假设；承担', explain: 'to think that sth is true without proof' }, { en: 'atmosphere', zh: '气氛；大气层', explain: 'the feeling that a place gives you' }, { en: 'attach', zh: '附上；连接', explain: 'to join one thing to another' }, { en: 'attempt', zh: '尝试；企图', explain: 'an act of trying to do sth' }, { en: 'attend', zh: '参加；出席', explain: 'to be present at an event' }, { en: 'attitude', zh: '态度；看法', explain: 'the way you think and feel about sth' }, { en: 'attract', zh: '吸引；引起', explain: 'to make sb interested in sth' }, { en: 'authority', zh: '权威；当局', explain: 'the power to give orders' }, { en: 'available', zh: '可用的；有效的', explain: 'able to be used or obtained' }, { en: 'average', zh: '平均的；普通的', explain: 'calculated by adding amounts together' }, { en: 'avoid', zh: '避免；回避', explain: 'to keep away from sb/sth' }, { en: 'award', zh: '奖励；奖品', explain: 'a prize given for an achievement' }, { en: 'aware', zh: '意识到的；知道的', explain: 'knowing that sth exists' }, { en: 'balance', zh: '平衡；余额', explain: 'a state where things are equal' }, { en: 'ban', zh: '禁止；禁令', explain: 'to officially say sth is not allowed' }, { en: 'barrier', zh: '障碍；屏障', explain: 'sth that prevents movement or access' }, { en: 'behalf', zh: '代表；利益', explain: 'on behalf of: as a representative of' }, { en: 'behave', zh: '行为；表现', explain: 'to act in a particular way' }, { en: 'belief', zh: '信念；信仰', explain: 'a feeling that sth is true' }, { en: 'belong', zh: '属于；归属', explain: 'to be in the right place' }, { en: 'benefit', zh: '利益；好处', explain: 'an advantage or helpful effect' }, { en: 'blame', zh: '责备；归咎于', explain: 'to say sb is responsible for sth bad' }, { en: 'border', zh: '边界；边境', explain: 'the line dividing two countries' }, { en: 'bother', zh: '打扰；烦恼', explain: 'to make the effort to do sth' }, { en: 'boundary', zh: '边界；界限', explain: 'a real or imagined line that marks limits' }, { en: 'brand', zh: '品牌；商标', explain: 'a name given to a product by its maker' }, { en: 'broadcast', zh: '广播；播送', explain: 'to send out programmes on TV or radio' }, { en: 'budget', zh: '预算；经费', explain: 'the money available to spend' }, { en: 'burden', zh: '负担；重担', explain: 'a heavy load or responsibility' }, { en: 'campaign', zh: '运动；战役', explain: 'a planned set of activities for a goal' }, { en: 'cancel', zh: '取消', explain: 'to decide sth planned will not happen' }, { en: 'candidate', zh: '候选人', explain: 'sb who is trying to be elected' }, { en: 'capable', zh: '有能力的', explain: 'having the ability to do sth' }, { en: 'capacity', zh: '容量；能力', explain: 'the maximum amount sth can contain' }, { en: 'capture', zh: '捕获；俘获', explain: 'to catch sb/sth and keep them as prisoner' }, { en: 'career', zh: '职业；生涯', explain: 'the job series you do in your life' }, { en: 'category', zh: '类别；范畴', explain: 'a group of people or things of the same type' }, { en: 'celebrate', zh: '庆祝；赞美', explain: 'to show that an event is special' }, { en: 'challenge', zh: '挑战；质疑', explain: 'sth difficult that tests your ability' }, { en: 'champion', zh: '冠军；捍卫者', explain: 'sb who has won a competition' }, { en: 'channel', zh: '频道；渠道；海峡', explain: 'a television station' }, { en: 'character', zh: '性格；角色', explain: 'the qualities that make sb different' }, { en: 'characteristic', zh: '特征；特点', explain: 'a typical quality or feature' }, { en: 'circumstance', zh: '环境；情况', explain: 'the conditions affecting a situation' }, { en: 'claim', zh: '声称；要求', explain: 'to state that sth is true' }, { en: 'classify', zh: '分类；归类', explain: 'to arrange things into groups' }, { en: 'climate', zh: '气候', explain: 'the typical weather conditions of an area' }, { en: 'collapse', zh: '倒塌；崩溃', explain: 'to fall down suddenly' }, { en: 'colleague', zh: '同事', explain: 'sb you work with' }, { en: 'combine', zh: '结合；联合', explain: 'to join things together' }, { en: 'comfort', zh: '舒适；安慰', explain: 'a pleasant feeling of being relaxed' }, { en: 'command', zh: '命令；指挥', explain: 'an order given to sb' }, { en: 'comment', zh: '评论；意见', explain: 'an opinion about sb/sth' }, { en: 'commission', zh: '委员会；佣金', explain: 'a group of people given authority' }, { en: 'commit', zh: '犯(罪)；承诺', explain: 'to do sth wrong or illegal' }, { en: 'committee', zh: '委员会', explain: 'a group chosen to make decisions' }, { en: 'communicate', zh: '交流；沟通', explain: 'to share information with others' }, { en: 'community', zh: '社区；团体', explain: 'all the people living in a particular area' }, { en: 'companion', zh: '同伴；伙伴', explain: 'sb you spend time with or travel with' }, { en: 'compare', zh: '比较；对照', explain: 'to examine how things are similar/different' }, { en: 'compensate', zh: '补偿；赔偿', explain: 'to pay money for loss or damage' }, { en: 'compete', zh: '竞争；比赛', explain: 'to try to be more successful than others' }, { en: 'competent', zh: '胜任的', explain: 'having enough skill or knowledge' }, { en: 'complaint', zh: '抱怨；投诉', explain: 'a statement that sth is wrong' }, { en: 'complex', zh: '复杂的；综合体', explain: 'made of many different parts' }, { en: 'component', zh: '组成部分；零件', explain: 'one of several parts of a whole' }, { en: 'concentrate', zh: '集中；专注', explain: 'to give all your attention to sth' }, { en: 'concept', zh: '概念；观念', explain: 'an idea or principle' }, { en: 'concern', zh: '关心；涉及', explain: 'a feeling of worry about sth' }, { en: 'conclude', zh: '总结；结束', explain: 'to decide sth after thinking' }, { en: 'conduct', zh: '行为；指挥', explain: 'to carry out a particular activity' }, { en: 'confidence', zh: '信心；信任', explain: 'the feeling that you can trust sb/sth' }, { en: 'confirm', zh: '确认；证实', explain: 'to prove that sth is true' }, { en: 'conflict', zh: '冲突；矛盾', explain: 'a serious disagreement' }, { en: 'confuse', zh: '困惑；混淆', explain: 'to make sb unable to think clearly' }, { en: 'connect', zh: '连接；联系', explain: 'to join two or more things together' }, { en: 'conscious', zh: '有意识的；清醒的', explain: 'aware of what is happening around you' }, { en: 'consequence', zh: '后果；结果', explain: 'a result of a particular action' }, { en: 'conservative', zh: '保守的', explain: 'not liking sudden changes' }, { en: 'consider', zh: '考虑；认为', explain: 'to think about sth carefully' }, { en: 'consist', zh: '由…组成', explain: 'to be formed from the things mentioned' }, { en: 'constant', zh: '不断的；恒定的', explain: 'happening all the time' }, { en: 'constitute', zh: '构成；组成', explain: 'to be the parts that form sth' }, { en: 'construct', zh: '建造；构建', explain: 'to build or make sth' }, { en: 'consume', zh: '消费；消耗', explain: 'to use sth, especially fuel or energy' }, { en: 'contact', zh: '接触；联系', explain: 'to communicate with sb' }, { en: 'contain', zh: '包含；容纳', explain: 'to have sth inside or as part of it' }, { en: 'contemporary', zh: '当代的', explain: 'belonging to the present time' }, { en: 'content', zh: '内容；满意的', explain: 'the things that are inside sth' }, { en: 'context', zh: '上下文；背景', explain: 'the situation in which sth happens' }, { en: 'continue', zh: '继续；持续', explain: 'to keep happening without stopping' }, { en: 'contract', zh: '合同；收缩', explain: 'a formal written agreement' }, { en: 'contrast', zh: '对比；对照', explain: 'a clear difference between things' }, { en: 'contribute', zh: '贡献；捐献', explain: 'to give sth to help achieve sth' }, { en: 'convenient', zh: '方便；便利', explain: 'easy to use or suitable for a purpose' }, { en: 'convention', zh: '惯例；大会', explain: 'a usual way of behaving' }, { en: 'convince', zh: '说服；使确信', explain: 'to make sb believe sth is true' }, { en: 'cooperate', zh: '合作；协作', explain: 'to work together for a common purpose' }, { en: 'correspond', zh: '对应；通信', explain: 'to match or be similar to sth' }, { en: 'create', zh: '创造；创建', explain: 'to make sth new happen or exist' }, { en: 'credit', zh: '信用；赞扬', explain: 'praise because of sth good you did' }, { en: 'crime', zh: '犯罪；罪行', explain: 'an illegal act punishable by law' }, { en: 'crisis', zh: '危机', explain: 'a time of great danger or difficulty' }, { en: 'criticize', zh: '批评；评论', explain: 'to say what you think is bad about sth' }, { en: 'crucial', zh: '至关重要的', explain: 'extremely important' }, { en: 'culture', zh: '文化；教养', explain: 'the customs and beliefs of a group' }, { en: 'currency', zh: '货币；通货', explain: 'the money used in a particular country' }, { en: 'current', zh: '当前的；水流', explain: 'happening or existing now' }, { en: 'cycle', zh: '循环；周期', explain: 'a series of events that repeat regularly' },
        ]
    },

    ielts: {
        name: '雅思/托福', emoji: '🌍',
        data: [
            { en: 'phenomenon', zh: '现象', explain: 'a fact or event that can be observed' }, { en: 'philosophy', zh: '哲学', explain: 'the study of knowledge and existence' }, { en: 'plausible', zh: '似乎合理的', explain: 'seeming likely to be true' }, { en: 'pole', zh: '杆；极地', explain: 'a long thin piece of wood or metal' }, { en: 'ponder', zh: '沉思；考虑', explain: 'to think about carefully' }, { en: 'portion', zh: '部分；一份', explain: 'a part of a larger amount' }, { en: 'portray', zh: '描绘；扮演', explain: 'to show or describe in a particular way' }, { en: 'pose', zh: '造成；摆姿势', explain: 'to create a threat or problem' }, { en: 'posture', zh: '姿势；态度', explain: 'the position of your body when standing' }, { en: 'potential', zh: '潜力；潜在的', explain: 'possible in the future' }, { en: 'practitioner', zh: '从业者', explain: 'sb who works in a profession' }, { en: 'precede', zh: '先于…', explain: 'to happen before sth' }, { en: 'precipitate', zh: '加速；沉淀', explain: 'to make sth happen suddenly' }, { en: 'precise', zh: '精确的', explain: 'exact and accurate' }, { en: 'preclude', zh: '阻止；排除', explain: 'to prevent sth from happening' }, { en: 'predominant', zh: '主要的', explain: 'having more power or influence' }, { en: 'preliminary', zh: '初步的', explain: 'coming before the main part' }, { en: 'premise', zh: '前提', explain: 'a statement that forms the basis' }, { en: 'prescribe', zh: '开处方；规定', explain: 'to say what medicine sb needs' }, { en: 'preserve', zh: '保护；保存', explain: 'to keep in its original state' }, { en: 'prestige', zh: '声望', explain: 'the respect that sb/sth has' }, { en: 'presume', zh: '假设', explain: 'to suppose sth is true without proof' }, { en: 'prevail', zh: '盛行；占优势', explain: 'to exist or be widespread' }, { en: 'prevalent', zh: '流行的', explain: 'existing very commonly' }, { en: 'primitive', zh: '原始的', explain: 'belonging to an early stage of development' }, { en: 'principal', zh: '主要的；校长', explain: 'most important' }, { en: 'principle', zh: '原则', explain: 'a moral rule or belief about behaviour' }, { en: 'priority', zh: '优先', explain: 'sth that is more important than others' }, { en: 'probe', zh: '探查；探究', explain: 'to ask questions to discover facts' }, { en: 'proceed', zh: '继续；进行', explain: 'to continue doing sth' }, { en: 'proclaim', zh: '宣布；声明', explain: 'to announce officially and publicly' }, { en: 'proficiency', zh: '熟练；精通', explain: 'a high degree of skill' }, { en: 'profile', zh: '轮廓；简介', explain: 'a short description of sb/sth' }, { en: 'profound', zh: '深远的', explain: 'very great or intense' }, { en: 'prohibit', zh: '禁止', explain: 'to officially forbid sth' }, { en: 'prominent', zh: '突出的', explain: 'important and well-known' }, { en: 'prompt', zh: '促使；迅速的', explain: 'to cause sth to happen' }, { en: 'prone', zh: '有…倾向的', explain: 'likely to suffer from or do sth' }, { en: 'propagate', zh: '传播；繁殖', explain: 'to spread ideas to many people' }, { en: 'propel', zh: '推进', explain: 'to push forward' }, { en: 'proposition', zh: '提议', explain: 'an offer or suggestion' }, { en: 'prosecute', zh: '起诉', explain: 'to officially accuse sb of a crime' }, { en: 'prospect', zh: '前景；可能性', explain: 'the possibility that sth will happen' }, { en: 'prospective', zh: '预期的', explain: 'expected to happen in the future' }, { en: 'prosper', zh: '繁荣', explain: 'to be successful, especially financially' }, { en: 'provoke', zh: '激怒；引起', explain: 'to cause a strong reaction' }, { en: 'pursue', zh: '追求；追赶', explain: 'to try to achieve or follow' }, { en: 'quest', zh: '寻求；探索', explain: 'a long and difficult search' }, { en: 'random', zh: '随机的', explain: 'happening without a plan' }, { en: 'rational', zh: '理性的', explain: 'based on reason, not emotion' }, { en: 'realm', zh: '领域；王国', explain: 'an area of activity or knowledge' }, { en: 'reap', zh: '收获', explain: 'to get sth good as a result' }, { en: 'reassure', zh: '使安心', explain: 'to make sb feel less worried' }, { en: 'reconcile', zh: '调和；和解', explain: 'to make two ideas exist together' }, { en: 'refine', zh: '精炼；改善', explain: 'to improve by making small changes' }, { en: 'reinforce', zh: '加强', explain: 'to make a feeling or structure stronger' }, { en: 'reluctant', zh: '不情愿的', explain: 'not willing to do sth' }, { en: 'remedy', zh: '补救；治疗方法', explain: 'a way of dealing with a problem' }, { en: 'renaissance', zh: '文艺复兴', explain: 'a period of new growth of interest' }, { en: 'render', zh: '使成为；提供', explain: 'to cause sb/sth to be in a state' }, { en: 'repertoire', zh: '全部技能', explain: 'all the things sb can do' }, { en: 'replicate', zh: '复制', explain: 'to do again in the same way' }, { en: 'resemble', zh: '像；类似', explain: 'to look like or be similar to' }, { en: 'reserve', zh: '保留；预订', explain: 'to keep for a particular purpose' }, { en: 'reside', zh: '居住', explain: 'to live in a particular place' }, { en: 'resilient', zh: '有弹性的', explain: 'able to recover quickly from difficulties' }, { en: 'resolve', zh: '解决；决心', explain: 'to find a satisfactory solution' }, { en: 'resort', zh: '求助；度假胜地', explain: 'to use sth as a final choice' }, { en: 'restore', zh: '恢复', explain: 'to bring back to a former condition' }, { en: 'restrain', zh: '抑制', explain: 'to stop sb/sth from doing sth' }, { en: 'retain', zh: '保留', explain: 'to keep or continue to have' }, { en: 'retrieve', zh: '取回；检索', explain: 'to get sth back from a place' }, { en: 'revelation', zh: '启示；揭露', explain: 'a surprising fact made known' }, { en: 'revenue', zh: '收入；税收', explain: 'money that a business receives' }, { en: 'reverse', zh: '相反的；逆转', explain: 'to change sth to the opposite' }, { en: 'revolution', zh: '革命；旋转', explain: 'a great change in conditions' }, { en: 'rigorous', zh: '严格的', explain: 'demanding careful attention to rules' }, { en: 'ritual', zh: '仪式；惯例', explain: 'a set of fixed actions regularly performed' }, { en: 'rival', zh: '竞争对手', explain: 'sb competing with you for the same thing' }, { en: 'robust', zh: '强健的', explain: 'strong and healthy' }, { en: 'sanction', zh: '制裁；批准', explain: 'an official order to punish a country' }, { en: 'saturate', zh: '使饱和', explain: 'to fill completely so no more can be added' }, { en: 'scenario', zh: '情景；设想', explain: 'a possible future situation' }, { en: 'skeptical', zh: '怀疑的', explain: 'having doubts about sth' }, { en: 'solemn', zh: '庄严的', explain: 'very serious and sincere' }, { en: 'solicitor', zh: '律师', explain: 'a lawyer who prepares legal documents' }, { en: 'solidarity', zh: '团结', explain: 'support between people in a group' }, { en: 'sovereign', zh: '君主；至高无上的', explain: 'a king or queen' }, { en: 'speculate', zh: '推测；投机', explain: 'to guess without knowing all the facts' }, { en: 'sphere', zh: '球体；领域', explain: 'an area of activity or knowledge' }, { en: 'spontaneous', zh: '自发的', explain: 'happening naturally, not planned' }, { en: 'statistical', zh: '统计的', explain: 'relating to the use of numbers to represent facts' }, { en: 'stimulus', zh: '刺激', explain: 'sth that encourages activity' }, { en: 'straightforward', zh: '简单的', explain: 'easy to understand or do' }, { en: 'strategy', zh: '策略', explain: 'a long-term plan for success' }, { en: 'subordinate', zh: '下属的', explain: 'having a lower position than sb else' }, { en: 'subsidy', zh: '补贴', explain: 'money given by the government to help' }, { en: 'substantial', zh: '大量的', explain: 'large in amount or importance' }, { en: 'suffice', zh: '足够', explain: 'to be enough for a purpose' }, { en: 'superior', zh: '优越的；上级', explain: 'better than average or than others' }, { en: 'sustainable', zh: '可持续的', explain: 'able to continue without causing damage' }, { en: 'symbolic', zh: '象征的', explain: 'representing a particular idea' }, { en: 'synthetic', zh: '合成的', explain: 'made by combining chemical substances' },
        ]
    }
    ,
    gre: {
        name: 'GRE', emoji: '🏆',
        data: [
            { en: 'abate', zh: '减轻；减少', explain: 'to become less strong' },
            { en: 'aberration', zh: '异常；偏差', explain: 'a departure from normal' },
            { en: 'abeyance', zh: '搁置；中止', explain: 'temporary suspension' },
            { en: 'abjure', zh: '发誓放弃', explain: 'to renounce formally' },
            { en: 'ablution', zh: '洗礼；沐浴', explain: 'ritual washing' },
            { en: 'abnegation', zh: '克制；放弃', explain: 'self-denial' },
            { en: 'abominate', zh: '憎恶；厌恶', explain: 'to hate intensely' },
            { en: 'abortive', zh: '失败的；流产的', explain: 'failing to achieve' },
            { en: 'abrade', zh: '磨损；擦伤', explain: 'to wear away by friction' },
            { en: 'abridge', zh: '删节；缩短', explain: 'to shorten without losing sense' },
            { en: 'abrogate', zh: '废除；取消', explain: 'to abolish by authority' },
            { en: 'abscission', zh: '截断；切除', explain: 'the act of cutting off' },
            { en: 'abscond', zh: '潜逃；逃亡', explain: 'to escape secretly' },
            { en: 'absolve', zh: '赦免；免除', explain: 'to free from blame' },
            { en: 'abstemious', zh: '有节制的', explain: 'moderate in consumption' },
            { en: 'abstinence', zh: '节制；禁欲', explain: 'voluntary refraining' },
            { en: 'abstruse', zh: '深奥的；难解的', explain: 'hard to understand' },
            { en: 'abysmal', zh: '深不可测的；极糟的', explain: 'extremely bad' },
            { en: 'accede', zh: '同意；就任', explain: 'to agree to a demand' },
            { en: 'accolade', zh: '荣誉；赞美', explain: 'an award or praise' },
            { en: 'accost', zh: '搭讪；走近', explain: 'to approach and speak to' },
            { en: 'acerbic', zh: '尖刻的；酸的', explain: 'sharp and forthright' },
            { en: 'acme', zh: '顶点；极致', explain: 'the highest point' },
            { en: 'acquiesce', zh: '默许；顺从', explain: 'to accept without protest' },
            { en: 'acrid', zh: '辛辣的', explain: 'pungent in taste or smell' },
            { en: 'acrimony', zh: '尖刻；刻薄', explain: 'bitterness of manner' },
            { en: 'actuate', zh: '驱动机器；激励', explain: 'to make a machine work' },
            { en: 'acumen', zh: '敏锐；聪明', explain: 'keenness in judgment' },
            { en: 'adage', zh: '谚语；格言', explain: 'a wise traditional saying' },
            { en: 'adamant', zh: '坚定的；强硬的', explain: 'refusing to be persuaded' },
            { en: 'addle', zh: '使混乱；变坏', explain: 'to confuse or go bad' },
            { en: 'adjudicate', zh: '裁决；判决', explain: 'to reach a judicial decision' },
            { en: 'adjunct', zh: '附件；助手', explain: 'something auxiliary' },
            { en: 'admonish', zh: '告诫；警告', explain: 'to warn or reprimand firmly' },
            { en: 'adroit', zh: '灵巧的；机敏的', explain: 'clever or skillful' },
            { en: 'adulation', zh: '奉承；吹捧', explain: 'excessive flattery' },
            { en: 'adulterate', zh: '掺杂；掺假', explain: 'to make impure by adding' },
            { en: 'adumbrate', zh: '预示；遮蔽', explain: 'to outline or foreshadow' },
            { en: 'adventitious', zh: '偶然的；外来的', explain: 'happening by chance' },
            { en: 'aegis', zh: '保护；庇护', explain: 'protection or support' },
            { en: 'affable', zh: '和蔼可亲的', explain: 'friendly and easy to talk to' },
            { en: 'affectation', zh: '做作；假装', explain: 'artificial behavior' },
            { en: 'aggrandize', zh: '夸大；增强', explain: 'to increase power or status' },
            { en: 'aghast', zh: '惊骇的', explain: 'filled with horror' },
            { en: 'agrarian', zh: '农业的', explain: 'relating to farming' },
            { en: 'alacrity', zh: '欣然；敏捷', explain: 'cheerful eagerness' },
            { en: 'alchemy', zh: '炼金术；魔力', explain: 'medieval chemistry' },
            { en: 'algorithm', zh: '算法', explain: 'a step-by-step procedure' },
            { en: 'allay', zh: '减轻；缓和', explain: 'to reduce fear or worry' },
            { en: 'allege', zh: '宣称；断言', explain: 'to claim without proof' },
            { en: 'allegiance', zh: '忠诚；效忠', explain: 'loyalty to a group' },
            { en: 'alleviate', zh: '减轻；缓和', explain: 'to make pain less severe' },
            { en: 'alloy', zh: '合金', explain: 'a mix of metals' },
            { en: 'allude', zh: '暗示；间接提及', explain: 'to refer indirectly' },
            { en: 'allure', zh: '诱惑；吸引', explain: 'powerful attraction' },
            { en: 'aloof', zh: '冷漠的；疏远的', explain: 'emotionally distant' },
            { en: 'altercation', zh: '争吵；口角', explain: 'a heated argument' },
            { en: 'altruism', zh: '利他主义', explain: 'unselfish concern' },
            { en: 'amalgamate', zh: '合并；混合', explain: 'to combine into one' },
            { en: 'amass', zh: '积聚；收集', explain: 'to gather a large amount' },
            { en: 'amazon', zh: '亚马逊', explain: 'a South American river and rainforest' },
            { en: 'ambiguous', zh: '模糊的；含糊的', explain: 'having more than one meaning' },
            { en: 'ambivalence', zh: '矛盾心理', explain: 'mixed feelings' },
            { en: 'ameliorate', zh: '改善；改良', explain: 'to make something better' },
            { en: 'amenable', zh: '顺从的；易响应的', explain: 'willing to agree' },
            { en: 'amiable', zh: '和蔼的；友善的', explain: 'friendly and pleasant' },
            { en: 'amicable', zh: '友善的；和平的', explain: 'characterized by friendliness' },
            { en: 'amnesty', zh: '大赦；特赦', explain: 'an official pardon' },
            { en: 'amorphous', zh: '无定形的', explain: 'without clear shape' },
            { en: 'amortize', zh: '分期偿还', explain: 'to pay off a debt gradually' },
            { en: 'amulet', zh: '护身符', explain: 'a protective charm' },
            { en: 'anachronism', zh: '时代错误', explain: 'belonging to another time' },
            { en: 'analgesic', zh: '镇痛药', explain: 'pain-relieving drug' },
            { en: 'analogous', zh: '相似的', explain: 'similar in some way' },
            { en: 'anarchy', zh: '无政府状态', explain: 'absence of government' },
            { en: 'anathema', zh: '诅咒；厌恶', explain: 'something profoundly hated' },
            { en: 'ancillary', zh: '辅助的；附属的', explain: 'providing support' },
            { en: 'anecdote', zh: '轶事；趣闻', explain: 'a short amusing story' },
            { en: 'anhydrous', zh: '无水的', explain: 'containing no water' },
            { en: 'animosity', zh: '敌意；憎恶', explain: 'strong hostility' },
            { en: 'annals', zh: '年鉴；编年史', explain: 'yearly historical records' },
            { en: 'annex', zh: '吞并；附加', explain: 'to add or take territory' },
            { en: 'annihilate', zh: '消灭；歼灭', explain: 'to destroy completely' },
            { en: 'annotate', zh: '注释；评注', explain: 'to add notes to text' },
            { en: 'anomaly', zh: '异常；反常', explain: 'something unusual or irregular' },
            { en: 'anonymity', zh: '匿名', explain: 'the state of being unknown' },
            { en: 'antagonism', zh: '对抗；敌意', explain: 'active hostility' },
            { en: 'antedate', zh: '早于；先于', explain: 'to come before in time' },
            { en: 'anthology', zh: '选集；文选', explain: 'a collection of works' },
            { en: 'antipathy', zh: '反感；厌恶', explain: 'a deep feeling of dislike' },
            { en: 'antithesis', zh: '对立面；对照', explain: 'the exact opposite' },
            { en: 'apathy', zh: '冷漠；无兴趣', explain: 'lack of interest or emotion' },
            { en: 'aperture', zh: '孔；光圈', explain: 'an opening or hole' },
            { en: 'apex', zh: '顶点；尖端', explain: 'the very top or highest point' },
        ]
    },

    business: {
        name: '商务', emoji: '💼',
        data: [
            { en: 'acquisition', zh: '收购；获得', explain: 'buying another company' },
            { en: 'affiliate', zh: '附属机构', explain: 'a connected organization' },
            { en: 'agenda', zh: '议程', explain: 'a list of items to discuss' },
            { en: 'allocate', zh: '分配', explain: 'to distribute resources' },
            { en: 'amortization', zh: '摊销', explain: 'spreading costs over time' },
            { en: 'arbitrage', zh: '套利', explain: 'simultaneous buying and selling' },
            { en: 'asset', zh: '资产', explain: 'something valuable owned' },
            { en: 'audit', zh: '审计', explain: 'an official examination of accounts' },
            { en: 'bankruptcy', zh: '破产', explain: 'legal inability to pay debts' },
            { en: 'benchmark', zh: '基准；标杆', explain: 'a standard for comparison' },
            { en: 'bid', zh: '投标；出价', explain: 'an offer to buy or provide services' },
            { en: 'bond', zh: '债券', explain: 'a debt investment' },
            { en: 'brand', zh: '品牌', explain: 'a product identity' },
            { en: 'breakeven', zh: '收支平衡', explain: 'point of zero profit and loss' },
            { en: 'broker', zh: '经纪人', explain: 'an intermediary in transactions' },
            { en: 'budget', zh: '预算', explain: 'a financial plan' },
            { en: 'bundle', zh: '捆绑销售', explain: 'to sell products together' },
            { en: 'capital', zh: '资本；资金', explain: 'financial assets or resources' },
            { en: 'cartel', zh: '卡特尔；垄断联盟', explain: 'a group controlling prices' },
            { en: 'cashflow', zh: '现金流', explain: 'movement of money in and out' },
            { en: 'commodity', zh: '商品；大宗商品', explain: 'a raw material or product' },
            { en: 'consolidate', zh: '合并；巩固', explain: 'to combine into a stronger unit' },
            { en: 'consumer', zh: '消费者', explain: 'a person who buys goods' },
            { en: 'contingent', zh: '偶然的；取决于', explain: 'dependent on something else' },
            { en: 'corporation', zh: '公司；企业', explain: 'a large business entity' },
            { en: 'costing', zh: '成本核算', explain: 'calculation of production costs' },
            { en: 'counterpart', zh: '对应方；对手', explain: 'a person or thing matching another' },
            { en: 'credit', zh: '信贷；信用', explain: 'ability to borrow or trust' },
            { en: 'currency', zh: '货币；通货', explain: 'money used in a country' },
            { en: 'debenture', zh: '债券；信用债券', explain: 'a long-term debt instrument' },
            { en: 'deficit', zh: '赤字；亏损', explain: 'spending exceeding income' },
            { en: 'delegate', zh: '委派；代表', explain: 'to entrust a task to someone' },
            { en: 'demographic', zh: '人口统计的', explain: 'relating to population groups' },
            { en: 'depreciation', zh: '折旧；贬值', explain: 'decrease in value over time' },
            { en: 'derivative', zh: '衍生品', explain: 'a financial contract based on an asset' },
            { en: 'disburse', zh: '支付；支出', explain: 'to pay out money' },
            { en: 'disposable', zh: '可支配的', explain: 'available for use or spending' },
            { en: 'dividend', zh: '股息；红利', explain: 'a share of company profits' },
            { en: 'downsize', zh: '裁员；缩小规模', explain: 'to reduce workforce or size' },
            { en: 'due diligence', zh: '尽职调查', explain: 'thorough investigation before a deal' },
            { en: 'equity', zh: '股权；权益', explain: 'ownership in a company' },
            { en: 'escrow', zh: '第三方托管', explain: 'a third-party holding arrangement' },
            { en: 'exempt', zh: '免除；豁免', explain: 'free from an obligation' },
            { en: 'expenditure', zh: '支出；开销', explain: 'the spending of money' },
            { en: 'fiscal', zh: '财政的', explain: 'relating to government finances' },
            { en: 'franchise', zh: '特许经营权', explain: 'a license to operate a business' },
            { en: 'futures', zh: '期货', explain: 'contracts for future delivery' },
            { en: 'gross', zh: '总的；毛的', explain: 'total before deductions' },
            { en: 'hedge', zh: '对冲', explain: 'to protect against financial loss' },
            { en: 'holding', zh: '持股；控股公司', explain: 'a company owning other companies' },
            { en: 'incentive', zh: '激励；奖励', explain: 'something that motivates action' },
            { en: 'indemnify', zh: '赔偿；补偿', explain: 'to compensate for loss' },
            { en: 'inflation', zh: '通货膨胀', explain: 'general increase in prices' },
            { en: 'infrastructure_', zh: '基础设施', explain: 'basic physical systems' },
            { en: 'insolvent', zh: '资不抵债', explain: 'unable to pay debts' },
            { en: 'insurance', zh: '保险', explain: 'protection against risk' },
            { en: 'intangible', zh: '无形的（资产）', explain: 'non-physical, like goodwill' },
            { en: 'inventory', zh: '库存', explain: 'goods held for sale' },
            { en: 'invoice', zh: '发票', explain: 'a bill for goods or services' },
            { en: 'joint venture', zh: '合资企业', explain: 'a business partnership' },
            { en: 'jurisdiction', zh: '管辖权', explain: 'official legal authority' },
            { en: 'leverage', zh: '杠杆；利用', explain: 'using borrowed capital or influence' },
            { en: 'liability', zh: '负债；责任', explain: 'a financial obligation' },
            { en: 'liquidation', zh: '清算；变现', explain: 'converting assets into cash' },
            { en: 'logo', zh: '标志；商标', explain: 'a graphic symbol of a brand' },
            { en: 'logistics', zh: '物流；后勤', explain: 'management of goods flow' },
            { en: 'margin', zh: '利润；保证金', explain: 'difference between cost and price' },
            { en: 'market share', zh: '市场份额', explain: '% of total market sales' },
            { en: 'merger', zh: '合并；兼并', explain: 'combining of two companies' },
            { en: 'monopoly', zh: '垄断', explain: 'exclusive control of a market' },
            { en: 'mortgage', zh: '抵押贷款', explain: 'a loan secured by property' },
            { en: 'negotiate', zh: '谈判；协商', explain: 'to discuss to reach agreement' },
            { en: 'niche', zh: '细分市场；利基', explain: 'a specialized market segment' },
            { en: 'notary', zh: '公证人', explain: 'a person authorized to certify documents' },
            { en: 'oligopoly', zh: '寡头垄断', explain: 'market controlled by few sellers' },
            { en: 'outsource', zh: '外包', explain: 'to contract work externally' },
            { en: 'overhead', zh: '管理费用', explain: 'ongoing business expenses' },
            { en: 'patent', zh: '专利', explain: 'exclusive right to an invention' },
            { en: 'payroll', zh: '工资单；薪资', explain: 'total employee wages' },
            { en: 'portfolio', zh: '投资组合；作品集', explain: 'a collection of investments or work' },
            { en: 'premium', zh: '溢价；保费', explain: 'an additional amount paid' },
            { en: 'procurement', zh: '采购', explain: 'process of obtaining goods' },
            { en: 'profitability', zh: '盈利能力', explain: 'ability to generate profit' },
            { en: 'prospectus', zh: '招股说明书', explain: 'a document for potential investors' },
            { en: 'quota', zh: '配额；限额', explain: 'a limited share or amount' },
            { en: 'rebate', zh: '回扣；退款', explain: 'a partial refund' },
            { en: 'recession', zh: '经济衰退', explain: 'a period of economic decline' },
            { en: 'reconcile', zh: '对账；调和', explain: 'to make accounts agree' },
            { en: 'remittance', zh: '汇款', explain: 'money sent to someone' },
            { en: 'retail', zh: '零售', explain: 'selling directly to customers' },
            { en: 'revenue', zh: '收入；营收', explain: 'total income from business' },
            { en: 'royalty', zh: '版税；专利费', explain: 'payment for use of intellectual property' },
            { en: 'shareholder', zh: '股东', explain: 'an owner of company stock' },
            { en: 'solvent', zh: '有偿付能力的', explain: 'able to pay all debts' },
            { en: 'stakeholder', zh: '利益相关者', explain: 'anyone affected by a business' },
            { en: 'subsidiary', zh: '子公司', explain: 'a company controlled by a parent' },
            { en: 'supply chain', zh: '供应链', explain: 'network of producing and delivering' },
            { en: 'surplus', zh: '盈余；顺差', explain: 'an amount more than needed' },
            { en: 'tariff', zh: '关税', explain: 'a tax on imports or exports' },
            { en: 'tenure', zh: '任期；保有权', explain: 'period of holding a position' },
            { en: 'trademark', zh: '商标', explain: 'a registered symbol or name' },
            { en: 'turnover', zh: '营业额；流动率', explain: 'total sales or staff changes' },
            { en: 'venture capital', zh: '风险投资', explain: 'funding for startups' },
            { en: 'volatile', zh: '波动的；易变的', explain: 'likely to change suddenly' },
            { en: 'wholesale', zh: '批发', explain: 'selling in large quantities' },
            { en: 'workflow', zh: '工作流程', explain: 'the sequence of tasks' },
        ]
    },

    academic: {
        name: '学术', emoji: '🔬',
        data: [
            { en: 'abstract', zh: '摘要；抽象的', explain: 'a summary of research' },
            { en: 'academia', zh: '学术界', explain: 'the world of scholarship' },
            { en: 'accord', zh: '一致；协定', explain: 'agreement or harmony' },
            { en: 'adhere', zh: '遵守；黏附', explain: 'to stick firmly or follow' },
            { en: 'adjacent', zh: '邻近的', explain: 'next to or adjoining' },
            { en: 'aesthetic', zh: '审美的；美学的', explain: 'concerned with beauty' },
            { en: 'aggregate', zh: '总计；聚集体', explain: 'a whole formed by combining' },
            { en: 'agrarian_', zh: '农业的；土地的', explain: 'relating to cultivated land' },
            { en: 'albeit', zh: '虽然；尽管', explain: 'although, even though' },
            { en: 'algorithm_', zh: '算法；运算法则', explain: 'a set of rules for solving problems' },
            { en: 'alienate', zh: '使疏远', explain: 'to cause to feel isolated' },
            { en: 'analogy', zh: '类比；相似', explain: 'a comparison between two things' },
            { en: 'ancillary_', zh: '辅助的', explain: 'providing supplementary support' },
            { en: 'annotate_', zh: '注释；注解', explain: 'to add explanatory notes' },
            { en: 'anomaly_', zh: '异常；不规则', explain: 'something that deviates from normal' },
            { en: 'antecedent', zh: '前例；先行词', explain: 'something preceding another' },
            { en: 'anthology_', zh: '选集；文集', explain: 'a published collection of writings' },
            { en: 'antithesis_', zh: '对立面', explain: 'the direct opposite' },
            { en: 'apparatus', zh: '仪器；装置', explain: 'technical equipment' },
            { en: 'append', zh: '附加；增补', explain: 'to add as a supplement' },
            { en: 'arbitrary', zh: '任意的；武断的', explain: 'based on random choice' },
            { en: 'archetype', zh: '原型；典型', explain: 'an original model or pattern' },
            { en: 'assimilate', zh: '同化；吸收', explain: 'to take in and fully understand' },
            { en: 'asymmetry', zh: '不对称', explain: 'lack of equal proportion' },
            { en: 'attribute', zh: '属性；归因于', explain: 'a quality or feature' },
            { en: 'augment', zh: '增大；加强', explain: 'to make greater by adding' },
            { en: 'autonomous', zh: '自治的；自主的', explain: 'self-governing' },
            { en: 'axiom', zh: '公理；原理', explain: 'a self-evident truth' },
            { en: 'baseline', zh: '基线；基准', explain: 'a starting point for comparison' },
            { en: 'behavioural', zh: '行为的', explain: 'relating to behavior' },
            { en: 'bibliography', zh: '参考书目', explain: 'a list of sources used' },
            { en: 'bilateral', zh: '双边的', explain: 'involving two sides' },
            { en: 'binary', zh: '二元的；二进制的', explain: 'consisting of two parts' },
            { en: 'brevity', zh: '简洁；短暂', explain: 'conciseness of expression' },
            { en: 'canonical', zh: '正统的；规范的', explain: 'accepted as authoritative' },
            { en: 'catalyst', zh: '催化剂；促进因素', explain: 'something that speeds up a process' },
            { en: 'caveat', zh: '警告；附加说明', explain: 'a warning or condition' },
            { en: 'chronicle', zh: '编年史；记录', explain: 'a historical account' },
            { en: 'circumvent', zh: '规避；绕过', explain: 'to find a way around' },
            { en: 'citation', zh: '引用；引文', explain: 'a reference to a source' },
            { en: 'clarity', zh: '清晰；明晰', explain: 'the quality of being clear' },
            { en: 'coherent', zh: '连贯的；一致的', explain: 'logically organized' },
            { en: 'cohort', zh: '群体；队列', explain: 'a group of people with shared characteristics' },
            { en: 'collaborate', zh: '合作；协作', explain: 'to work jointly' },
            { en: 'comparative', zh: '比较的；相对的', explain: 'measured by comparison' },
            { en: 'compile', zh: '编纂；编译', explain: 'to produce by assembling' },
            { en: 'complement', zh: '补充；补足', explain: 'something that completes' },
            { en: 'composite', zh: '复合的；合成物', explain: 'made up of several parts' },
            { en: 'concise', zh: '简洁的；简明的', explain: 'giving information briefly' },
            { en: 'conducive', zh: '有益的；促进的', explain: 'making something likely' },
            { en: 'congruent', zh: '一致的；全等的', explain: 'in agreement or harmony' },
            { en: 'conjecture', zh: '推测；猜测', explain: 'an opinion based on incomplete evidence' },
            { en: 'consensus_', zh: '共识；一致意见', explain: 'general agreement' },
            { en: 'constrain_', zh: '限制；约束', explain: 'to restrict or limit' },
            { en: 'contend_', zh: '主张；竞争', explain: 'to assert or compete' },
            { en: 'contextual', zh: '上下文的；背景的', explain: 'relating to surrounding text or situation' },
            { en: 'continuum', zh: '连续体；光谱', explain: 'a continuous sequence' },
            { en: 'converge_', zh: '汇聚；趋向', explain: 'to come together at a point' },
            { en: 'conversely', zh: '相反地', explain: 'in an opposite way' },
            { en: 'correlate_', zh: '关联；相关', explain: 'to have a mutual relationship' },
            { en: 'critique', zh: '评论；批判', explain: 'a detailed analysis and assessment' },
            { en: 'cumulative', zh: '累积的', explain: 'increasing by successive additions' },
            { en: 'curriculum', zh: '课程', explain: 'the subjects in a course' },
            { en: 'deductive', zh: '演绎的', explain: 'reasoning from general to specific' },
            { en: 'delineate', zh: '描绘；描述', explain: 'to describe precisely' },
            { en: 'demarcation', zh: '划分界限', explain: 'the act of setting boundaries' },
            { en: 'denote', zh: '表示；意味着', explain: 'to be a sign of' },
            { en: 'depict', zh: '描绘；描述', explain: 'to represent in words or pictures' },
            { en: 'determinant', zh: '决定因素', explain: 'a factor that determines outcome' },
            { en: 'dichotomy', zh: '二分法；对立', explain: 'a division into two opposed parts' },
            { en: 'discourse', zh: '话语；论述', explain: 'written or spoken communication' },
            { en: 'discrete', zh: '离散的；独立的', explain: 'individually separate' },
            { en: 'disparity', zh: '差异；悬殊', explain: 'a great difference' },
            { en: 'disseminate', zh: '传播；散布', explain: 'to spread widely' },
            { en: 'dogma', zh: '教条；信条', explain: 'an unquestioned principle' },
            { en: 'eclectic', zh: '折中的；兼收的', explain: 'deriving from diverse sources' },
            { en: 'elicit', zh: '引出；诱出', explain: 'to draw out a response' },
            { en: 'elucidate', zh: '阐明；解释', explain: 'to make clear' },
            { en: 'embody', zh: '体现；包含', explain: 'to give concrete form to' },
            { en: 'empirical', zh: '经验的；实证的', explain: 'based on observation' },
            { en: 'enumerate', zh: '列举；枚举', explain: 'to list one by one' },
            { en: 'epistemology', zh: '认识论', explain: 'the theory of knowledge' },
            { en: 'equivocal', zh: '模棱两可的', explain: 'open to interpretation' },
            { en: 'ergo', zh: '因此；所以', explain: 'therefore' },
            { en: 'eschew', zh: '避开；戒除', explain: 'to deliberately avoid' },
            { en: 'etymology', zh: '词源学', explain: 'the study of word origins' },
            { en: 'exacerbate', zh: '加剧；恶化', explain: 'to make worse' },
            { en: 'exemplify', zh: '例证；示范', explain: 'to serve as an example' },
            { en: 'explicit', zh: '明确的；直白的', explain: 'stated clearly and exactly' },
            { en: 'exponent', zh: '倡导者；指数', explain: 'a person who advocates' },
            { en: 'extrapolate', zh: '推断；外推', explain: 'to estimate beyond known data' },
            { en: 'facet', zh: '方面；切面', explain: 'one aspect of something' },
            { en: 'feasible', zh: '可行的', explain: 'possible and practical' },
            { en: 'fluctuate', zh: '波动；起伏', explain: 'to vary irregularly' },
        ]
    },

    daily: {
        name: '日常', emoji: '🏠',
        data: [
            { en: 'acquaintance', zh: '熟人；相识', explain: 'a person one knows slightly' },
            { en: 'adolescent', zh: '青少年', explain: 'a young person' },
            { en: 'agony', zh: '极大痛苦', explain: 'extreme suffering' },
            { en: 'aisle', zh: '走廊；过道', explain: 'a passage between rows' },
            { en: 'allergy', zh: '过敏', explain: 'an immune overreaction' },
            { en: 'allowance', zh: '津贴；零花钱', explain: 'a regular amount of money given' },
            { en: 'altitude', zh: '海拔；高度', explain: 'height above sea level' },
            { en: 'apologize', zh: '道歉', explain: 'to express regret' },
            { en: 'appetite', zh: '食欲；胃口', explain: 'a desire to eat' },
            { en: 'appliance', zh: '家用电器', explain: 'a household machine' },
            { en: 'appreciate', zh: '感激；欣赏', explain: 'to recognize the value' },
            { en: 'architecture', zh: '建筑；架构', explain: 'the design of buildings' },
            { en: 'aroma', zh: '芳香；香味', explain: 'a pleasant smell' },
            { en: 'athletic', zh: '运动的；健壮的', explain: 'physically strong' },
            { en: 'atmosphere', zh: '氛围；大气', explain: 'the character or mood' },
            { en: 'auction', zh: '拍卖', explain: 'a public sale' },
            { en: 'auditorium', zh: '礼堂；观众席', explain: 'a large room for audiences' },
            { en: 'authentic', zh: '真正的；可靠的', explain: 'of undisputed origin' },
            { en: 'backup', zh: '备份', explain: 'a spare copy' },
            { en: 'balcony', zh: '阳台', explain: 'an outdoor platform' },
            { en: 'bargain', zh: '便宜货；讨价还价', explain: 'a good deal' },
            { en: 'beverage', zh: '饮料', explain: 'a drink' },
            { en: 'boutique', zh: '精品店', explain: 'a small fashionable store' },
            { en: 'brochure', zh: '宣传册', explain: 'a small booklet' },
            { en: 'browse', zh: '浏览；翻阅', explain: 'to look through casually' },
            { en: 'budget_', zh: '预算；经费', explain: 'a spending plan' },
            { en: 'cafeteria', zh: '自助餐厅', explain: 'a self-service restaurant' },
            { en: 'calculator', zh: '计算器', explain: 'an electronic computing device' },
            { en: 'campaign', zh: '活动；战役', explain: 'an organized course of action' },
            { en: 'catering', zh: '餐饮服务', explain: 'providing food service' },
            { en: 'caution', zh: '谨慎；警告', explain: 'care taken to avoid danger' },
            { en: 'celebrity', zh: '名人', explain: 'a famous person' },
            { en: 'certificate', zh: '证书；证明', explain: 'an official document' },
            { en: 'chore', zh: '家务杂事', explain: 'a routine household task' },
            { en: 'commute', zh: '通勤', explain: 'to travel to work regularly' },
            { en: 'compassion', zh: '同情；怜悯', explain: 'sympathetic concern' },
            { en: 'compliment', zh: '赞美；问候', explain: 'a polite expression of praise' },
            { en: 'congestion', zh: '拥堵；充血', explain: 'overcrowding or blockage' },
            { en: 'cosmetic', zh: '化妆品；美容的', explain: 'beauty product or appearance-enhancing' },
            { en: 'coupon', zh: '优惠券', explain: 'a discount voucher' },
            { en: 'courtesy_', zh: '礼貌；恩惠', explain: 'polite behavior' },
            { en: 'cuisine', zh: '烹饪；菜系', explain: 'a style of cooking' },
            { en: 'custody', zh: '监护；保管', explain: 'protective care or control' },
            { en: 'deadline', zh: '截止日期', explain: 'the latest time to finish' },
            { en: 'decent', zh: '得体的；正派的', explain: 'of an acceptable standard' },
            { en: 'decorate', zh: '装饰；装修', explain: 'to make something look attractive' },
            { en: 'departure', zh: '出发；离开', explain: 'the act of leaving' },
            { en: 'destination', zh: '目的地', explain: 'the place one is going to' },
            { en: 'diagnosis', zh: '诊断', explain: 'identification of an illness' },
            { en: 'dilemma', zh: '困境；两难', explain: 'a difficult choice' },
            { en: 'discipline', zh: '纪律；学科', explain: 'training to follow rules' },
            { en: 'discount', zh: '折扣', explain: 'a price reduction' },
            { en: 'disinfect', zh: '消毒', explain: 'to clean by killing germs' },
            { en: 'dispatch', zh: '派遣；发送', explain: 'to send off quickly' },
            { en: 'diverse', zh: '多样的；不同的', explain: 'showing great variety' },
            { en: 'domestic', zh: '国内的；家庭的', explain: 'relating to home or country' },
            { en: 'dosage', zh: '剂量；用量', explain: 'the amount of medicine' },
            { en: 'drastic', zh: '激烈的；极端的', explain: 'extreme in effect' },
            { en: 'drowsy', zh: '困倦的', explain: 'feeling sleepy' },
            { en: 'durable', zh: '耐用的', explain: 'long-lasting' },
            { en: 'edible', zh: '可食用的', explain: 'fit to be eaten' },
            { en: 'embassy', zh: '大使馆', explain: 'a diplomatic mission' },
            { en: 'emergency', zh: '紧急情况', explain: 'a serious, unexpected situation' },
            { en: 'empathy', zh: '同理心；共鸣', explain: 'understanding others feelings' },
            { en: 'enrollment', zh: '注册；入学', explain: 'the act of signing up' },
            { en: 'errand', zh: '差事；跑腿', explain: 'a short trip to do something' },
            { en: 'escalator', zh: '自动扶梯', explain: 'a moving staircase' },
            { en: 'etiquette', zh: '礼仪；礼节', explain: 'rules of polite behavior' },
            { en: 'excursion', zh: '远足；短途旅行', explain: 'a short trip for pleasure' },
            { en: 'expiration', zh: '到期；截止', explain: 'the ending of a fixed period' },
            { en: 'fabulous', zh: '极好的；惊人的', explain: 'extraordinarily good' },
            { en: 'fatigue', zh: '疲劳；疲惫', explain: 'extreme tiredness' },
            { en: 'fiance', zh: '未婚夫', explain: 'a man engaged to be married' },
            { en: 'flexible', zh: '灵活的；柔韧的', explain: 'able to bend easily' },
            { en: 'fragile', zh: '易碎的；脆弱的', explain: 'easily broken' },
            { en: 'friction', zh: '摩擦；冲突', explain: 'rubbing or conflict' },
            { en: 'gadget', zh: '小器具；小玩意', explain: 'a small useful device' },
            { en: 'genuine', zh: '真诚的；真正的', explain: 'truly what it is said to be' },
            { en: 'gesture', zh: '手势；姿态', explain: 'a movement expressing meaning' },
            { en: 'glimpse', zh: '一瞥；瞥见', explain: 'a brief look' },
            { en: 'gorgeous', zh: '华丽的；极好的', explain: 'very beautiful' },
            { en: 'gossip', zh: '闲话；八卦', explain: 'casual talk about others' },
            { en: 'gourmet', zh: '美食家', explain: 'a connoisseur of fine food' },
            { en: 'gratitude', zh: '感激；感谢', explain: 'the feeling of being thankful' },
            { en: 'grooming', zh: '打扮；修饰', explain: 'keeping oneself neat and clean' },
            { en: 'guarantee', zh: '保证；担保', explain: 'a formal assurance' },
            { en: 'habitat', zh: '栖息地；生活环境', explain: 'the natural home of an organism' },
            { en: 'handicraft', zh: '手工艺品', explain: 'an item made by hand' },
            { en: 'hazard', zh: '危险；危害', explain: 'a danger or risk' },
            { en: 'headline', zh: '头条新闻；标题', explain: 'the main news title' },
            { en: 'heritage', zh: '遗产；传统', explain: 'cultural inheritance' },
            { en: 'hibernate', zh: '冬眠；休眠', explain: 'to sleep through winter' },
            { en: 'hygiene', zh: '卫生；保健', explain: 'conditions for healthy living' },
            { en: 'ignite', zh: '点燃；激发', explain: 'to set on fire or spark' },
            { en: 'illuminate', zh: '照亮；阐明', explain: 'to light up or clarify' },
            { en: 'imitate', zh: '模仿；仿效', explain: 'to copy someone or something' },
            { en: 'immune', zh: '免疫的；豁免的', explain: 'resistant to infection' },
            { en: 'indulge', zh: '纵容；沉迷', explain: 'to allow oneself enjoyment' },
            { en: 'ingredient', zh: '成分；原料', explain: 'a component of a mixture' },
        ]
    },

    technology: {
        name: '科技', emoji: '💻',
        data: [
            { en: 'algorithm__', zh: '算法', explain: 'step-by-step procedure for calculation' },
            { en: 'analytics', zh: '数据分析', explain: 'systematic computational data analysis' },
            { en: 'anonymous', zh: '匿名的', explain: 'without a known identity' },
            { en: 'antenna', zh: '天线', explain: 'a device for transmitting signals' },
            { en: 'application', zh: '应用程序', explain: 'a computer program with a user interface' },
            { en: 'archive', zh: '存档；档案', explain: 'a collection of historical records' },
            { en: 'artificial', zh: '人造的；人工的', explain: 'made by humans, not natural' },
            { en: 'authentication', zh: '认证；验证', explain: 'process of verifying identity' },
            { en: 'automation', zh: '自动化', explain: 'the use of automatic equipment' },
            { en: 'avatar', zh: '头像；化身', explain: 'a digital representation of a user' },
            { en: 'bandwidth', zh: '带宽', explain: 'the data transfer capacity' },
            { en: 'binary__', zh: '二进制的；双重的', explain: 'using only digits 0 and 1' },
            { en: 'biometric', zh: '生物识别', explain: 'using physical characteristics for ID' },
            { en: 'blockchain', zh: '区块链', explain: 'decentralized digital ledger' },
            { en: 'bot', zh: '机器人程序', explain: 'an automated software program' },
            { en: 'browser_', zh: '浏览器', explain: 'software for viewing web pages' },
            { en: 'bug', zh: '程序错误', explain: 'a coding error in software' },
            { en: 'cache', zh: '缓存', explain: 'temporary storage for quick access' },
            { en: 'chip', zh: '芯片', explain: 'a tiny integrated circuit' },
            { en: 'cloud', zh: '云（存储）', explain: 'remote internet-based storage' },
            { en: 'compatible', zh: '兼容的', explain: 'able to work together' },
            { en: 'compress', zh: '压缩', explain: 'to reduce file size' },
            { en: 'console', zh: '控制台', explain: 'a panel for controlling equipment' },
            { en: 'cryptography', zh: '密码学', explain: 'the art of writing codes' },
            { en: 'cursor', zh: '光标', explain: 'a movable indicator on a screen' },
            { en: 'dashboard', zh: '仪表板', explain: 'a visual display of information' },
            { en: 'database', zh: '数据库', explain: 'organized collection of data' },
            { en: 'debug', zh: '调试', explain: 'to find and fix errors in code' },
            { en: 'deploy', zh: '部署', explain: 'to put software into production' },
            { en: 'developer', zh: '开发者', explain: 'someone who writes software' },
            { en: 'device', zh: '设备；装置', explain: 'a piece of equipment' },
            { en: 'digital', zh: '数字的；数码的', explain: 'using discrete electronic signals' },
            { en: 'domain', zh: '域名；领域', explain: 'an internet address' },
            { en: 'download', zh: '下载', explain: 'to transfer data from a server' },
            { en: 'encrypt', zh: '加密', explain: 'to convert data into code' },
            { en: 'firmware', zh: '固件', explain: 'permanent software in hardware' },
            { en: 'framework', zh: '框架', explain: 'a basic structure for software' },
            { en: 'gateway', zh: '网关', explain: 'a network connection point' },
            { en: 'graphics', zh: '图形', explain: 'visual images produced by computer' },
            { en: 'hardware', zh: '硬件', explain: 'physical computer components' },
            { en: 'hosting', zh: '托管', explain: 'providing server space' },
            { en: 'interface', zh: '界面；接口', explain: 'a connection point between systems' },
            { en: 'kernel', zh: '内核', explain: 'the core of an operating system' },
            { en: 'latency', zh: '延迟', explain: 'the delay in data transmission' },
            { en: 'malware', zh: '恶意软件', explain: 'harmful software' },
            { en: 'module', zh: '模块', explain: 'a self-contained unit of code' },
            { en: 'network', zh: '网络', explain: 'connected computers for data sharing' },
            { en: 'plugin', zh: '插件', explain: 'an add-on software component' },
            { en: 'protocol', zh: '协议', explain: 'a set of rules for data transfer' },
            { en: 'repository', zh: '存储库；仓库', explain: 'a storage location for code or data' },
            { en: 'resolution', zh: '分辨率', explain: 'the detail level of an image' },
            { en: 'router', zh: '路由器', explain: 'a network traffic director' },
            { en: 'scalable', zh: '可扩展的', explain: 'able to grow in capacity' },
            { en: 'server', zh: '服务器', explain: 'a computer providing services' },
            { en: 'software', zh: '软件', explain: 'computer programs' },
            { en: 'spam', zh: '垃圾邮件', explain: 'unsolicited bulk messages' },
            { en: 'storage', zh: '存储', explain: 'a place to keep data' },
            { en: 'streaming', zh: '流媒体', explain: 'transmitting data in real-time' },
            { en: 'synchronize', zh: '同步', explain: 'to make match in time' },
            { en: 'syntax', zh: '语法；句法', explain: 'the rules of language structure' },
            { en: 'throughput', zh: '吞吐量', explain: 'the amount of data processed' },
            { en: 'upload', zh: '上传', explain: 'to transfer data to a server' },
            { en: 'virtual', zh: '虚拟的', explain: 'simulated by a computer' },
            { en: 'vulnerability', zh: '漏洞；脆弱性', explain: 'a weakness in security' },
            { en: 'widget', zh: '小部件', explain: 'a small application or tool' },
        ]
    },
};

// ==================== 词库辅助函数 ====================
function getLibraryKeys() { return Object.keys(WORD_LIBRARIES); }
function getLibraryInfo(key) {
    const lib = WORD_LIBRARIES[key];
    return lib ? { key, name: lib.name, emoji: lib.emoji, count: lib.data.length } : null;
}

function lookupTranslation(word) {
    const lower = word.toLowerCase();
    for (const key of Object.keys(WORD_LIBRARIES)) {
        const found = WORD_LIBRARIES[key].data.find(w => w.en.toLowerCase() === lower);
        if (found) return found.zh;
    }
    if (typeof getUserLibrary === 'function') {
        const ul = getUserLibrary();
        const found = ul.find(w => w.en.toLowerCase() === lower);
        if (found) return found.zh;
    }
    return null;
}

// 新增：获取英文释义
function lookupExplain(word) {
    const lower = word.toLowerCase();
    for (const key of Object.keys(WORD_LIBRARIES)) {
        const found = WORD_LIBRARIES[key].data.find(w => w.en.toLowerCase() === lower);
        if (found && found.explain) return found.explain;
    }
    if (typeof getUserLibrary === 'function') {
        const ul = getUserLibrary();
        const found = ul.find(w => w.en.toLowerCase() === lower);
        if (found && found.explain) return found.explain;
    }
    return null;
}

// 向后兼容 WORDS_DATA（自动包含所有已加载词库）
function rebuildWordsData() {
    const merged = []; const seen = new Set();
    const order = ['cet4_new', 'cet6_new', 'senior', 'ielts', 'gre', 'gre_ext', 'toefl', 'business', 'academic', 'daily', 'technology'];
    const levelMap = { cet4_new: 1, senior: 1, cet6_new: 2, ielts: 2, gre: 3, gre_ext: 3, toefl: 3, business: 2, academic: 3, daily: 1, technology: 2 };
    for (const key of order) {
        const lib = WORD_LIBRARIES[key];
        if (!lib || !lib.data) continue;
        for (const w of lib.data) {
            if (!seen.has(w.en.toLowerCase())) {
                seen.add(w.en.toLowerCase());
                merged.push({ en: w.en, zh: w.zh, explain: w.explain || '', level: levelMap[key] || 1 });
            }
        }
    }
    // 更新全局 WORDS_DATA
    if (typeof WORDS_DATA !== 'undefined') {
        WORDS_DATA.length = 0;
        Array.prototype.push.apply(WORDS_DATA, merged);
    }
    return merged;
}

var WORDS_DATA = rebuildWordsData();
