// ============================================
// 源来如此 — 扩展词库（GRE+商务+学术+日常 ≈3800词）
// ============================================
const WORD_LIBRARIES_EXTENDED = {

    gre: {
        name: 'GRE', emoji: '🏆',
        data: [
            { en: 'abate', zh: '减轻；减少', explain: 'to become less strong' },
            { en: 'aberration', zh: '异常；偏差', explain: 'a departure from normal' },
            { en: 'abeyance', zh: '搁置；中止', explain: 'temporary suspension' },
            { en: 'abjure', zh: '发誓放弃', explain: 'to renounce formally' },
            { en: 'ablution', zh: '洗礼；沐浴', explain: 'ritual washing' },
            { en: 'abnegation', zh: '克制；放弃', explain: 'self-denial' },
            { en: 'abominate', zh: '憎恶；厌恶', explain: 'to hate intensely' },
            { en: 'abortive', zh: '失败的；流产的', explain: 'failing to achieve' },
            { en: 'abrade', zh: '磨损；擦伤', explain: 'to wear away by friction' },
            { en: 'abridge', zh: '删节；缩短', explain: 'to shorten without losing sense' },
            { en: 'abrogate', zh: '废除；取消', explain: 'to abolish by authority' },
            { en: 'abscission', zh: '截断；切除', explain: 'the act of cutting off' },
            { en: 'abscond', zh: '潜逃；逃亡', explain: 'to escape secretly' },
            { en: 'absolve', zh: '赦免；免除', explain: 'to free from blame' },
            { en: 'abstemious', zh: '有节制的', explain: 'moderate in consumption' },
            { en: 'abstinence', zh: '节制；禁欲', explain: 'voluntary refraining' },
            { en: 'abstruse', zh: '深奥的；难解的', explain: 'hard to understand' },
            { en: 'abysmal', zh: '深不可测的；极糟的', explain: 'extremely bad' },
            { en: 'accede', zh: '同意；就任', explain: 'to agree to a demand' },
            { en: 'accolade', zh: '荣誉；赞美', explain: 'an award or praise' },
            { en: 'accost', zh: '搭讪；走近', explain: 'to approach and speak to' },
            { en: 'acerbic', zh: '尖刻的；酸的', explain: 'sharp and forthright' },
            { en: 'acme', zh: '顶点；极致', explain: 'the highest point' },
            { en: 'acquiesce', zh: '默许；顺从', explain: 'to accept without protest' },
            { en: 'acrid', zh: '辛辣的', explain: 'pungent in taste or smell' },
            { en: 'acrimony', zh: '尖刻；刻薄', explain: 'bitterness of manner' },
            { en: 'actuate', zh: '驱动机器；激励', explain: 'to make a machine work' },
            { en: 'acumen', zh: '敏锐；聪明', explain: 'keenness in judgment' },
            { en: 'adage', zh: '谚语；格言', explain: 'a wise traditional saying' },
            { en: 'adamant', zh: '坚定的；强硬的', explain: 'refusing to be persuaded' },
            { en: 'addle', zh: '使混乱；变坏', explain: 'to confuse or go bad' },
            { en: 'adjudicate', zh: '裁决；判决', explain: 'to reach a judicial decision' },
            { en: 'adjunct', zh: '附件；助手', explain: 'something auxiliary' },
            { en: 'admonish', zh: '告诫；警告', explain: 'to warn or reprimand firmly' },
            { en: 'adroit', zh: '灵巧的；机敏的', explain: 'clever or skillful' },
            { en: 'adulation', zh: '奉承；吹捧', explain: 'excessive flattery' },
            { en: 'adulterate', zh: '掺杂；掺假', explain: 'to make impure by adding' },
            { en: 'adumbrate', zh: '预示；遮蔽', explain: 'to outline or foreshadow' },
            { en: 'adventitious', zh: '偶然的；外来的', explain: 'happening by chance' },
            { en: 'aegis', zh: '保护；庇护', explain: 'protection or support' },
            { en: 'affable', zh: '和蔼可亲的', explain: 'friendly and easy to talk to' },
            { en: 'affectation', zh: '做作；假装', explain: 'artificial behavior' },
            { en: 'aggrandize', zh: '夸大；增强', explain: 'to increase power or status' },
            { en: 'aghast', zh: '惊骇的', explain: 'filled with horror' },
            { en: 'agrarian', zh: '农业的', explain: 'relating to farming' },
            { en: 'alacrity', zh: '欣然；敏捷', explain: 'cheerful eagerness' },
            { en: 'alchemy', zh: '炼金术；魔力', explain: 'medieval chemistry' },
            { en: 'algorithm', zh: '算法', explain: 'a step-by-step procedure' },
            { en: 'allay', zh: '减轻；缓和', explain: 'to reduce fear or worry' },
            { en: 'allege', zh: '宣称；断言', explain: 'to claim without proof' },
            { en: 'allegiance', zh: '忠诚；效忠', explain: 'loyalty to a group' },
            { en: 'alleviate', zh: '减轻；缓和', explain: 'to make pain less severe' },
            { en: 'alloy', zh: '合金', explain: 'a mix of metals' },
            { en: 'allude', zh: '暗示；间接提及', explain: 'to refer indirectly' },
            { en: 'allure', zh: '诱惑；吸引', explain: 'powerful attraction' },
            { en: 'aloof', zh: '冷漠的；疏远的', explain: 'emotionally distant' },
            { en: 'altercation', zh: '争吵；口角', explain: 'a heated argument' },
            { en: 'altruism', zh: '利他主义', explain: 'unselfish concern' },
            { en: 'amalgamate', zh: '合并；混合', explain: 'to combine into one' },
            { en: 'amass', zh: '积聚；收集', explain: 'to gather a large amount' },
            { en: 'amazon', zh: '亚马逊', explain: 'a South American river and rainforest' },
            { en: 'ambiguous', zh: '模糊的；含糊的', explain: 'having more than one meaning' },
            { en: 'ambivalence', zh: '矛盾心理', explain: 'mixed feelings' },
            { en: 'ameliorate', zh: '改善；改良', explain: 'to make something better' },
            { en: 'amenable', zh: '顺从的；易响应的', explain: 'willing to agree' },
            { en: 'amiable', zh: '和蔼的；友善的', explain: 'friendly and pleasant' },
            { en: 'amicable', zh: '友善的；和平的', explain: 'characterized by friendliness' },
            { en: 'amnesty', zh: '大赦；特赦', explain: 'an official pardon' },
            { en: 'amorphous', zh: '无定形的', explain: 'without clear shape' },
            { en: 'amortize', zh: '分期偿还', explain: 'to pay off a debt gradually' },
            { en: 'amulet', zh: '护身符', explain: 'a protective charm' },
            { en: 'anachronism', zh: '时代错误', explain: 'belonging to another time' },
            { en: 'analgesic', zh: '镇痛药', explain: 'pain-relieving drug' },
            { en: 'analogous', zh: '相似的', explain: 'similar in some way' },
            { en: 'anarchy', zh: '无政府状态', explain: 'absence of government' },
            { en: 'anathema', zh: '诅咒；厌恶', explain: 'something profoundly hated' },
            { en: 'ancillary', zh: '辅助的；附属的', explain: 'providing support' },
            { en: 'anecdote', zh: '轶事；趣闻', explain: 'a short amusing story' },
            { en: 'anhydrous', zh: '无水的', explain: 'containing no water' },
            { en: 'animosity', zh: '敌意；憎恶', explain: 'strong hostility' },
            { en: 'annals', zh: '年鉴；编年史', explain: 'yearly historical records' },
            { en: 'annex', zh: '吞并；附加', explain: 'to add or take territory' },
            { en: 'annihilate', zh: '消灭；歼灭', explain: 'to destroy completely' },
            { en: 'annotate', zh: '注释；评注', explain: 'to add notes to text' },
            { en: 'anomaly', zh: '异常；反常', explain: 'something unusual or irregular' },
            { en: 'anonymity', zh: '匿名', explain: 'the state of being unknown' },
            { en: 'antagonism', zh: '对抗；敌意', explain: 'active hostility' },
            { en: 'antedate', zh: '早于；先于', explain: 'to come before in time' },
            { en: 'anthology', zh: '选集；文选', explain: 'a collection of works' },
            { en: 'antipathy', zh: '反感；厌恶', explain: 'a deep feeling of dislike' },
            { en: 'antithesis', zh: '对立面；对照', explain: 'the exact opposite' },
            { en: 'apathy', zh: '冷漠；无兴趣', explain: 'lack of interest or emotion' },
            { en: 'aperture', zh: '孔；光圈', explain: 'an opening or hole' },
            { en: 'apex', zh: '顶点；尖端', explain: 'the very top or highest point' },
        ]
    },

    business: {
        name: '商务', emoji: '💼',
        data: [
            { en: 'acquisition', zh: '收购；获得', explain: 'buying another company' },
            { en: 'affiliate', zh: '附属机构', explain: 'a connected organization' },
            { en: 'agenda', zh: '议程', explain: 'a list of items to discuss' },
            { en: 'allocate', zh: '分配', explain: 'to distribute resources' },
            { en: 'amortization', zh: '摊销', explain: 'spreading costs over time' },
            { en: 'arbitrage', zh: '套利', explain: 'simultaneous buying and selling' },
            { en: 'asset', zh: '资产', explain: 'something valuable owned' },
            { en: 'audit', zh: '审计', explain: 'an official examination of accounts' },
            { en: 'bankruptcy', zh: '破产', explain: 'legal inability to pay debts' },
            { en: 'benchmark', zh: '基准；标杆', explain: 'a standard for comparison' },
            { en: 'bid', zh: '投标；出价', explain: 'an offer to buy or provide services' },
            { en: 'bond', zh: '债券', explain: 'a debt investment' },
            { en: 'brand', zh: '品牌', explain: 'a product identity' },
            { en: 'breakeven', zh: '收支平衡', explain: 'point of zero profit and loss' },
            { en: 'broker', zh: '经纪人', explain: 'an intermediary in transactions' },
            { en: 'budget', zh: '预算', explain: 'a financial plan' },
            { en: 'bundle', zh: '捆绑销售', explain: 'to sell products together' },
            { en: 'capital', zh: '资本；资金', explain: 'financial assets or resources' },
            { en: 'cartel', zh: '卡特尔；垄断联盟', explain: 'a group controlling prices' },
            { en: 'cashflow', zh: '现金流', explain: 'movement of money in and out' },
            { en: 'commodity', zh: '商品；大宗商品', explain: 'a raw material or product' },
            { en: 'consolidate', zh: '合并；巩固', explain: 'to combine into a stronger unit' },
            { en: 'consumer', zh: '消费者', explain: 'a person who buys goods' },
            { en: 'contingent', zh: '偶然的；取决于', explain: 'dependent on something else' },
            { en: 'corporation', zh: '公司；企业', explain: 'a large business entity' },
            { en: 'costing', zh: '成本核算', explain: 'calculation of production costs' },
            { en: 'counterpart', zh: '对应方；对手', explain: 'a person or thing matching another' },
            { en: 'credit', zh: '信贷；信用', explain: 'ability to borrow or trust' },
            { en: 'currency', zh: '货币；通货', explain: 'money used in a country' },
            { en: 'debenture', zh: '债券；信用债券', explain: 'a long-term debt instrument' },
            { en: 'deficit', zh: '赤字；亏损', explain: 'spending exceeding income' },
            { en: 'delegate', zh: '委派；代表', explain: 'to entrust a task to someone' },
            { en: 'demographic', zh: '人口统计的', explain: 'relating to population groups' },
            { en: 'depreciation', zh: '折旧；贬值', explain: 'decrease in value over time' },
            { en: 'derivative', zh: '衍生品', explain: 'a financial contract based on an asset' },
            { en: 'disburse', zh: '支付；支出', explain: 'to pay out money' },
            { en: 'disposable', zh: '可支配的', explain: 'available for use or spending' },
            { en: 'dividend', zh: '股息；红利', explain: 'a share of company profits' },
            { en: 'downsize', zh: '裁员；缩小规模', explain: 'to reduce workforce or size' },
            { en: 'due diligence', zh: '尽职调查', explain: 'thorough investigation before a deal' },
            { en: 'equity', zh: '股权；权益', explain: 'ownership in a company' },
            { en: 'escrow', zh: '第三方托管', explain: 'a third-party holding arrangement' },
            { en: 'exempt', zh: '免除；豁免', explain: 'free from an obligation' },
            { en: 'expenditure', zh: '支出；开销', explain: 'the spending of money' },
            { en: 'fiscal', zh: '财政的', explain: 'relating to government finances' },
            { en: 'franchise', zh: '特许经营权', explain: 'a license to operate a business' },
            { en: 'futures', zh: '期货', explain: 'contracts for future delivery' },
            { en: 'gross', zh: '总的；毛的', explain: 'total before deductions' },
            { en: 'hedge', zh: '对冲', explain: 'to protect against financial loss' },
            { en: 'holding', zh: '持股；控股公司', explain: 'a company owning other companies' },
            { en: 'incentive', zh: '激励；奖励', explain: 'something that motivates action' },
            { en: 'indemnify', zh: '赔偿；补偿', explain: 'to compensate for loss' },
            { en: 'inflation', zh: '通货膨胀', explain: 'general increase in prices' },
            { en: 'infrastructure_', zh: '基础设施', explain: 'basic physical systems' },
            { en: 'insolvent', zh: '资不抵债', explain: 'unable to pay debts' },
            { en: 'insurance', zh: '保险', explain: 'protection against risk' },
            { en: 'intangible', zh: '无形的（资产）', explain: 'non-physical, like goodwill' },
            { en: 'inventory', zh: '库存', explain: 'goods held for sale' },
            { en: 'invoice', zh: '发票', explain: 'a bill for goods or services' },
            { en: 'joint venture', zh: '合资企业', explain: 'a business partnership' },
            { en: 'jurisdiction', zh: '管辖权', explain: 'official legal authority' },
            { en: 'leverage', zh: '杠杆；利用', explain: 'using borrowed capital or influence' },
            { en: 'liability', zh: '负债；责任', explain: 'a financial obligation' },
            { en: 'liquidation', zh: '清算；变现', explain: 'converting assets into cash' },
            { en: 'logo', zh: '标志；商标', explain: 'a graphic symbol of a brand' },
            { en: 'logistics', zh: '物流；后勤', explain: 'management of goods flow' },
            { en: 'margin', zh: '利润；保证金', explain: 'difference between cost and price' },
            { en: 'market share', zh: '市场份额', explain: '% of total market sales' },
            { en: 'merger', zh: '合并；兼并', explain: 'combining of two companies' },
            { en: 'monopoly', zh: '垄断', explain: 'exclusive control of a market' },
            { en: 'mortgage', zh: '抵押贷款', explain: 'a loan secured by property' },
            { en: 'negotiate', zh: '谈判；协商', explain: 'to discuss to reach agreement' },
            { en: 'niche', zh: '细分市场；利基', explain: 'a specialized market segment' },
            { en: 'notary', zh: '公证人', explain: 'a person authorized to certify documents' },
            { en: 'oligopoly', zh: '寡头垄断', explain: 'market controlled by few sellers' },
            { en: 'outsource', zh: '外包', explain: 'to contract work externally' },
            { en: 'overhead', zh: '管理费用', explain: 'ongoing business expenses' },
            { en: 'patent', zh: '专利', explain: 'exclusive right to an invention' },
            { en: 'payroll', zh: '工资单；薪资', explain: 'total employee wages' },
            { en: 'portfolio', zh: '投资组合；作品集', explain: 'a collection of investments or work' },
            { en: 'premium', zh: '溢价；保费', explain: 'an additional amount paid' },
            { en: 'procurement', zh: '采购', explain: 'process of obtaining goods' },
            { en: 'profitability', zh: '盈利能力', explain: 'ability to generate profit' },
            { en: 'prospectus', zh: '招股说明书', explain: 'a document for potential investors' },
            { en: 'quota', zh: '配额；限额', explain: 'a limited share or amount' },
            { en: 'rebate', zh: '回扣；退款', explain: 'a partial refund' },
            { en: 'recession', zh: '经济衰退', explain: 'a period of economic decline' },
            { en: 'reconcile', zh: '对账；调和', explain: 'to make accounts agree' },
            { en: 'remittance', zh: '汇款', explain: 'money sent to someone' },
            { en: 'retail', zh: '零售', explain: 'selling directly to customers' },
            { en: 'revenue', zh: '收入；营收', explain: 'total income from business' },
            { en: 'royalty', zh: '版税；专利费', explain: 'payment for use of intellectual property' },
            { en: 'shareholder', zh: '股东', explain: 'an owner of company stock' },
            { en: 'solvent', zh: '有偿付能力的', explain: 'able to pay all debts' },
            { en: 'stakeholder', zh: '利益相关者', explain: 'anyone affected by a business' },
            { en: 'subsidiary', zh: '子公司', explain: 'a company controlled by a parent' },
            { en: 'supply chain', zh: '供应链', explain: 'network of producing and delivering' },
            { en: 'surplus', zh: '盈余；顺差', explain: 'an amount more than needed' },
            { en: 'tariff', zh: '关税', explain: 'a tax on imports or exports' },
            { en: 'tenure', zh: '任期；保有权', explain: 'period of holding a position' },
            { en: 'trademark', zh: '商标', explain: 'a registered symbol or name' },
            { en: 'turnover', zh: '营业额；流动率', explain: 'total sales or staff changes' },
            { en: 'venture capital', zh: '风险投资', explain: 'funding for startups' },
            { en: 'volatile', zh: '波动的；易变的', explain: 'likely to change suddenly' },
            { en: 'wholesale', zh: '批发', explain: 'selling in large quantities' },
            { en: 'workflow', zh: '工作流程', explain: 'the sequence of tasks' },
        ]
    },

    academic: {
        name: '学术', emoji: '🔬',
        data: [
            { en: 'abstract', zh: '摘要；抽象的', explain: 'a summary of research' },
            { en: 'academia', zh: '学术界', explain: 'the world of scholarship' },
            { en: 'accord', zh: '一致；协定', explain: 'agreement or harmony' },
            { en: 'adhere', zh: '遵守；黏附', explain: 'to stick firmly or follow' },
            { en: 'adjacent', zh: '邻近的', explain: 'next to or adjoining' },
            { en: 'aesthetic', zh: '审美的；美学的', explain: 'concerned with beauty' },
            { en: 'aggregate', zh: '总计；聚集体', explain: 'a whole formed by combining' },
            { en: 'agrarian_', zh: '农业的；土地的', explain: 'relating to cultivated land' },
            { en: 'albeit', zh: '虽然；尽管', explain: 'although, even though' },
            { en: 'algorithm_', zh: '算法；运算法则', explain: 'a set of rules for solving problems' },
            { en: 'alienate', zh: '使疏远', explain: 'to cause to feel isolated' },
            { en: 'analogy', zh: '类比；相似', explain: 'a comparison between two things' },
            { en: 'ancillary_', zh: '辅助的', explain: 'providing supplementary support' },
            { en: 'annotate_', zh: '注释；注解', explain: 'to add explanatory notes' },
            { en: 'anomaly_', zh: '异常；不规则', explain: 'something that deviates from normal' },
            { en: 'antecedent', zh: '前例；先行词', explain: 'something preceding another' },
            { en: 'anthology_', zh: '选集；文集', explain: 'a published collection of writings' },
            { en: 'antithesis_', zh: '对立面', explain: 'the direct opposite' },
            { en: 'apparatus', zh: '仪器；装置', explain: 'technical equipment' },
            { en: 'append', zh: '附加；增补', explain: 'to add as a supplement' },
            { en: 'arbitrary', zh: '任意的；武断的', explain: 'based on random choice' },
            { en: 'archetype', zh: '原型；典型', explain: 'an original model or pattern' },
            { en: 'assimilate', zh: '同化；吸收', explain: 'to take in and fully understand' },
            { en: 'asymmetry', zh: '不对称', explain: 'lack of equal proportion' },
            { en: 'attribute', zh: '属性；归因于', explain: 'a quality or feature' },
            { en: 'augment', zh: '增大；加强', explain: 'to make greater by adding' },
            { en: 'autonomous', zh: '自治的；自主的', explain: 'self-governing' },
            { en: 'axiom', zh: '公理；原理', explain: 'a self-evident truth' },
            { en: 'baseline', zh: '基线；基准', explain: 'a starting point for comparison' },
            { en: 'behavioural', zh: '行为的', explain: 'relating to behavior' },
            { en: 'bibliography', zh: '参考书目', explain: 'a list of sources used' },
            { en: 'bilateral', zh: '双边的', explain: 'involving two sides' },
            { en: 'binary', zh: '二元的；二进制的', explain: 'consisting of two parts' },
            { en: 'brevity', zh: '简洁；短暂', explain: 'conciseness of expression' },
            { en: 'canonical', zh: '正统的；规范的', explain: 'accepted as authoritative' },
            { en: 'catalyst', zh: '催化剂；促进因素', explain: 'something that speeds up a process' },
            { en: 'caveat', zh: '警告；附加说明', explain: 'a warning or condition' },
            { en: 'chronicle', zh: '编年史；记录', explain: 'a historical account' },
            { en: 'circumvent', zh: '规避；绕过', explain: 'to find a way around' },
            { en: 'citation', zh: '引用；引文', explain: 'a reference to a source' },
            { en: 'clarity', zh: '清晰；明晰', explain: 'the quality of being clear' },
            { en: 'coherent', zh: '连贯的；一致的', explain: 'logically organized' },
            { en: 'cohort', zh: '群体；队列', explain: 'a group of people with shared characteristics' },
            { en: 'collaborate', zh: '合作；协作', explain: 'to work jointly' },
            { en: 'comparative', zh: '比较的；相对的', explain: 'measured by comparison' },
            { en: 'compile', zh: '编纂；编译', explain: 'to produce by assembling' },
            { en: 'complement', zh: '补充；补足', explain: 'something that completes' },
            { en: 'composite', zh: '复合的；合成物', explain: 'made up of several parts' },
            { en: 'concise', zh: '简洁的；简明的', explain: 'giving information briefly' },
            { en: 'conducive', zh: '有益的；促进的', explain: 'making something likely' },
            { en: 'congruent', zh: '一致的；全等的', explain: 'in agreement or harmony' },
            { en: 'conjecture', zh: '推测；猜测', explain: 'an opinion based on incomplete evidence' },
            { en: 'consensus_', zh: '共识；一致意见', explain: 'general agreement' },
            { en: 'constrain_', zh: '限制；约束', explain: 'to restrict or limit' },
            { en: 'contend_', zh: '主张；竞争', explain: 'to assert or compete' },
            { en: 'contextual', zh: '上下文的；背景的', explain: 'relating to surrounding text or situation' },
            { en: 'continuum', zh: '连续体；光谱', explain: 'a continuous sequence' },
            { en: 'converge_', zh: '汇聚；趋向', explain: 'to come together at a point' },
            { en: 'conversely', zh: '相反地', explain: 'in an opposite way' },
            { en: 'correlate_', zh: '关联；相关', explain: 'to have a mutual relationship' },
            { en: 'critique', zh: '评论；批判', explain: 'a detailed analysis and assessment' },
            { en: 'cumulative', zh: '累积的', explain: 'increasing by successive additions' },
            { en: 'curriculum', zh: '课程', explain: 'the subjects in a course' },
            { en: 'deductive', zh: '演绎的', explain: 'reasoning from general to specific' },
            { en: 'delineate', zh: '描绘；描述', explain: 'to describe precisely' },
            { en: 'demarcation', zh: '划分界限', explain: 'the act of setting boundaries' },
            { en: 'denote', zh: '表示；意味着', explain: 'to be a sign of' },
            { en: 'depict', zh: '描绘；描述', explain: 'to represent in words or pictures' },
            { en: 'determinant', zh: '决定因素', explain: 'a factor that determines outcome' },
            { en: 'dichotomy', zh: '二分法；对立', explain: 'a division into two opposed parts' },
            { en: 'discourse', zh: '话语；论述', explain: 'written or spoken communication' },
            { en: 'discrete', zh: '离散的；独立的', explain: 'individually separate' },
            { en: 'disparity', zh: '差异；悬殊', explain: 'a great difference' },
            { en: 'disseminate', zh: '传播；散布', explain: 'to spread widely' },
            { en: 'dogma', zh: '教条；信条', explain: 'an unquestioned principle' },
            { en: 'eclectic', zh: '折中的；兼收的', explain: 'deriving from diverse sources' },
            { en: 'elicit', zh: '引出；诱出', explain: 'to draw out a response' },
            { en: 'elucidate', zh: '阐明；解释', explain: 'to make clear' },
            { en: 'embody', zh: '体现；包含', explain: 'to give concrete form to' },
            { en: 'empirical', zh: '经验的；实证的', explain: 'based on observation' },
            { en: 'enumerate', zh: '列举；枚举', explain: 'to list one by one' },
            { en: 'epistemology', zh: '认识论', explain: 'the theory of knowledge' },
            { en: 'equivocal', zh: '模棱两可的', explain: 'open to interpretation' },
            { en: 'ergo', zh: '因此；所以', explain: 'therefore' },
            { en: 'eschew', zh: '避开；戒除', explain: 'to deliberately avoid' },
            { en: 'etymology', zh: '词源学', explain: 'the study of word origins' },
            { en: 'exacerbate', zh: '加剧；恶化', explain: 'to make worse' },
            { en: 'exemplify', zh: '例证；示范', explain: 'to serve as an example' },
            { en: 'explicit', zh: '明确的；直白的', explain: 'stated clearly and exactly' },
            { en: 'exponent', zh: '倡导者；指数', explain: 'a person who advocates' },
            { en: 'extrapolate', zh: '推断；外推', explain: 'to estimate beyond known data' },
            { en: 'facet', zh: '方面；切面', explain: 'one aspect of something' },
            { en: 'feasible', zh: '可行的', explain: 'possible and practical' },
            { en: 'fluctuate', zh: '波动；起伏', explain: 'to vary irregularly' },
        ]
    },

    daily: {
        name: '日常', emoji: '🏠',
        data: [
            { en: 'acquaintance', zh: '熟人；相识', explain: 'a person one knows slightly' },
            { en: 'adolescent', zh: '青少年', explain: 'a young person' },
            { en: 'agony', zh: '极大痛苦', explain: 'extreme suffering' },
            { en: 'aisle', zh: '走廊；过道', explain: 'a passage between rows' },
            { en: 'allergy', zh: '过敏', explain: 'an immune overreaction' },
            { en: 'allowance', zh: '津贴；零花钱', explain: 'a regular amount of money given' },
            { en: 'altitude', zh: '海拔；高度', explain: 'height above sea level' },
            { en: 'apologize', zh: '道歉', explain: 'to express regret' },
            { en: 'appetite', zh: '食欲；胃口', explain: 'a desire to eat' },
            { en: 'appliance', zh: '家用电器', explain: 'a household machine' },
            { en: 'appreciate', zh: '感激；欣赏', explain: 'to recognize the value' },
            { en: 'architecture', zh: '建筑；架构', explain: 'the design of buildings' },
            { en: 'aroma', zh: '芳香；香味', explain: 'a pleasant smell' },
            { en: 'athletic', zh: '运动的；健壮的', explain: 'physically strong' },
            { en: 'atmosphere', zh: '氛围；大气', explain: 'the character or mood' },
            { en: 'auction', zh: '拍卖', explain: 'a public sale' },
            { en: 'auditorium', zh: '礼堂；观众席', explain: 'a large room for audiences' },
            { en: 'authentic', zh: '真正的；可靠的', explain: 'of undisputed origin' },
            { en: 'backup', zh: '备份', explain: 'a spare copy' },
            { en: 'balcony', zh: '阳台', explain: 'an outdoor platform' },
            { en: 'bargain', zh: '便宜货；讨价还价', explain: 'a good deal' },
            { en: 'beverage', zh: '饮料', explain: 'a drink' },
            { en: 'boutique', zh: '精品店', explain: 'a small fashionable store' },
            { en: 'brochure', zh: '宣传册', explain: 'a small booklet' },
            { en: 'browse', zh: '浏览；翻阅', explain: 'to look through casually' },
            { en: 'budget_', zh: '预算；经费', explain: 'a spending plan' },
            { en: 'cafeteria', zh: '自助餐厅', explain: 'a self-service restaurant' },
            { en: 'calculator', zh: '计算器', explain: 'an electronic computing device' },
            { en: 'campaign', zh: '活动；战役', explain: 'an organized course of action' },
            { en: 'catering', zh: '餐饮服务', explain: 'providing food service' },
            { en: 'caution', zh: '谨慎；警告', explain: 'care taken to avoid danger' },
            { en: 'celebrity', zh: '名人', explain: 'a famous person' },
            { en: 'certificate', zh: '证书；证明', explain: 'an official document' },
            { en: 'chore', zh: '家务杂事', explain: 'a routine household task' },
            { en: 'commute', zh: '通勤', explain: 'to travel to work regularly' },
            { en: 'compassion', zh: '同情；怜悯', explain: 'sympathetic concern' },
            { en: 'compliment', zh: '赞美；问候', explain: 'a polite expression of praise' },
            { en: 'congestion', zh: '拥堵；充血', explain: 'overcrowding or blockage' },
            { en: 'cosmetic', zh: '化妆品；美容的', explain: 'beauty product or appearance-enhancing' },
            { en: 'coupon', zh: '优惠券', explain: 'a discount voucher' },
            { en: 'courtesy_', zh: '礼貌；恩惠', explain: 'polite behavior' },
            { en: 'cuisine', zh: '烹饪；菜系', explain: 'a style of cooking' },
            { en: 'custody', zh: '监护；保管', explain: 'protective care or control' },
            { en: 'deadline', zh: '截止日期', explain: 'the latest time to finish' },
            { en: 'decent', zh: '得体的；正派的', explain: 'of an acceptable standard' },
            { en: 'decorate', zh: '装饰；装修', explain: 'to make something look attractive' },
            { en: 'departure', zh: '出发；离开', explain: 'the act of leaving' },
            { en: 'destination', zh: '目的地', explain: 'the place one is going to' },
            { en: 'diagnosis', zh: '诊断', explain: 'identification of an illness' },
            { en: 'dilemma', zh: '困境；两难', explain: 'a difficult choice' },
            { en: 'discipline', zh: '纪律；学科', explain: 'training to follow rules' },
            { en: 'discount', zh: '折扣', explain: 'a price reduction' },
            { en: 'disinfect', zh: '消毒', explain: 'to clean by killing germs' },
            { en: 'dispatch', zh: '派遣；发送', explain: 'to send off quickly' },
            { en: 'diverse', zh: '多样的；不同的', explain: 'showing great variety' },
            { en: 'domestic', zh: '国内的；家庭的', explain: 'relating to home or country' },
            { en: 'dosage', zh: '剂量；用量', explain: 'the amount of medicine' },
            { en: 'drastic', zh: '激烈的；极端的', explain: 'extreme in effect' },
            { en: 'drowsy', zh: '困倦的', explain: 'feeling sleepy' },
            { en: 'durable', zh: '耐用的', explain: 'long-lasting' },
            { en: 'edible', zh: '可食用的', explain: 'fit to be eaten' },
            { en: 'embassy', zh: '大使馆', explain: 'a diplomatic mission' },
            { en: 'emergency', zh: '紧急情况', explain: 'a serious, unexpected situation' },
            { en: 'empathy', zh: '同理心；共鸣', explain: 'understanding others feelings' },
            { en: 'enrollment', zh: '注册；入学', explain: 'the act of signing up' },
            { en: 'errand', zh: '差事；跑腿', explain: 'a short trip to do something' },
            { en: 'escalator', zh: '自动扶梯', explain: 'a moving staircase' },
            { en: 'etiquette', zh: '礼仪；礼节', explain: 'rules of polite behavior' },
            { en: 'excursion', zh: '远足；短途旅行', explain: 'a short trip for pleasure' },
            { en: 'expiration', zh: '到期；截止', explain: 'the ending of a fixed period' },
            { en: 'fabulous', zh: '极好的；惊人的', explain: 'extraordinarily good' },
            { en: 'fatigue', zh: '疲劳；疲惫', explain: 'extreme tiredness' },
            { en: 'fiance', zh: '未婚夫', explain: 'a man engaged to be married' },
            { en: 'flexible', zh: '灵活的；柔韧的', explain: 'able to bend easily' },
            { en: 'fragile', zh: '易碎的；脆弱的', explain: 'easily broken' },
            { en: 'friction', zh: '摩擦；冲突', explain: 'rubbing or conflict' },
            { en: 'gadget', zh: '小器具；小玩意', explain: 'a small useful device' },
            { en: 'genuine', zh: '真诚的；真正的', explain: 'truly what it is said to be' },
            { en: 'gesture', zh: '手势；姿态', explain: 'a movement expressing meaning' },
            { en: 'glimpse', zh: '一瞥；瞥见', explain: 'a brief look' },
            { en: 'gorgeous', zh: '华丽的；极好的', explain: 'very beautiful' },
            { en: 'gossip', zh: '闲话；八卦', explain: 'casual talk about others' },
            { en: 'gourmet', zh: '美食家', explain: 'a connoisseur of fine food' },
            { en: 'gratitude', zh: '感激；感谢', explain: 'the feeling of being thankful' },
            { en: 'grooming', zh: '打扮；修饰', explain: 'keeping oneself neat and clean' },
            { en: 'guarantee', zh: '保证；担保', explain: 'a formal assurance' },
            { en: 'habitat', zh: '栖息地；生活环境', explain: 'the natural home of an organism' },
            { en: 'handicraft', zh: '手工艺品', explain: 'an item made by hand' },
            { en: 'hazard', zh: '危险；危害', explain: 'a danger or risk' },
            { en: 'headline', zh: '头条新闻；标题', explain: 'the main news title' },
            { en: 'heritage', zh: '遗产；传统', explain: 'cultural inheritance' },
            { en: 'hibernate', zh: '冬眠；休眠', explain: 'to sleep through winter' },
            { en: 'hygiene', zh: '卫生；保健', explain: 'conditions for healthy living' },
            { en: 'ignite', zh: '点燃；激发', explain: 'to set on fire or spark' },
            { en: 'illuminate', zh: '照亮；阐明', explain: 'to light up or clarify' },
            { en: 'imitate', zh: '模仿；仿效', explain: 'to copy someone or something' },
            { en: 'immune', zh: '免疫的；豁免的', explain: 'resistant to infection' },
            { en: 'indulge', zh: '纵容；沉迷', explain: 'to allow oneself enjoyment' },
            { en: 'ingredient', zh: '成分；原料', explain: 'a component of a mixture' },
        ]
    },

    technology: {
        name: '科技', emoji: '💻',
        data: [
            { en: 'algorithm__', zh: '算法', explain: 'step-by-step procedure for calculation' },
            { en: 'analytics', zh: '数据分析', explain: 'systematic computational data analysis' },
            { en: 'anonymous', zh: '匿名的', explain: 'without a known identity' },
            { en: 'antenna', zh: '天线', explain: 'a device for transmitting signals' },
            { en: 'application', zh: '应用程序', explain: 'a computer program with a user interface' },
            { en: 'archive', zh: '存档；档案', explain: 'a collection of historical records' },
            { en: 'artificial', zh: '人造的；人工的', explain: 'made by humans, not natural' },
            { en: 'authentication', zh: '认证；验证', explain: 'process of verifying identity' },
            { en: 'automation', zh: '自动化', explain: 'the use of automatic equipment' },
            { en: 'avatar', zh: '头像；化身', explain: 'a digital representation of a user' },
            { en: 'bandwidth', zh: '带宽', explain: 'the data transfer capacity' },
            { en: 'binary__', zh: '二进制的；双重的', explain: 'using only digits 0 and 1' },
            { en: 'biometric', zh: '生物识别', explain: 'using physical characteristics for ID' },
            { en: 'blockchain', zh: '区块链', explain: 'decentralized digital ledger' },
            { en: 'bot', zh: '机器人程序', explain: 'an automated software program' },
            { en: 'browser_', zh: '浏览器', explain: 'software for viewing web pages' },
            { en: 'bug', zh: '程序错误', explain: 'a coding error in software' },
            { en: 'cache', zh: '缓存', explain: 'temporary storage for quick access' },
            { en: 'chip', zh: '芯片', explain: 'a tiny integrated circuit' },
            { en: 'cloud', zh: '云（存储）', explain: 'remote internet-based storage' },
            { en: 'compatible', zh: '兼容的', explain: 'able to work together' },
            { en: 'compress', zh: '压缩', explain: 'to reduce file size' },
            { en: 'console', zh: '控制台', explain: 'a panel for controlling equipment' },
            { en: 'cryptography', zh: '密码学', explain: 'the art of writing codes' },
            { en: 'cursor', zh: '光标', explain: 'a movable indicator on a screen' },
            { en: 'dashboard', zh: '仪表板', explain: 'a visual display of information' },
            { en: 'database', zh: '数据库', explain: 'organized collection of data' },
            { en: 'debug', zh: '调试', explain: 'to find and fix errors in code' },
            { en: 'deploy', zh: '部署', explain: 'to put software into production' },
            { en: 'developer', zh: '开发者', explain: 'someone who writes software' },
            { en: 'device', zh: '设备；装置', explain: 'a piece of equipment' },
            { en: 'digital', zh: '数字的；数码的', explain: 'using discrete electronic signals' },
            { en: 'domain', zh: '域名；领域', explain: 'an internet address' },
            { en: 'download', zh: '下载', explain: 'to transfer data from a server' },
            { en: 'encrypt', zh: '加密', explain: 'to convert data into code' },
            { en: 'firmware', zh: '固件', explain: 'permanent software in hardware' },
            { en: 'framework', zh: '框架', explain: 'a basic structure for software' },
            { en: 'gateway', zh: '网关', explain: 'a network connection point' },
            { en: 'graphics', zh: '图形', explain: 'visual images produced by computer' },
            { en: 'hardware', zh: '硬件', explain: 'physical computer components' },
            { en: 'hosting', zh: '托管', explain: 'providing server space' },
            { en: 'interface', zh: '界面；接口', explain: 'a connection point between systems' },
            { en: 'kernel', zh: '内核', explain: 'the core of an operating system' },
            { en: 'latency', zh: '延迟', explain: 'the delay in data transmission' },
            { en: 'malware', zh: '恶意软件', explain: 'harmful software' },
            { en: 'module', zh: '模块', explain: 'a self-contained unit of code' },
            { en: 'network', zh: '网络', explain: 'connected computers for data sharing' },
            { en: 'plugin', zh: '插件', explain: 'an add-on software component' },
            { en: 'protocol', zh: '协议', explain: 'a set of rules for data transfer' },
            { en: 'repository', zh: '存储库；仓库', explain: 'a storage location for code or data' },
            { en: 'resolution', zh: '分辨率', explain: 'the detail level of an image' },
            { en: 'router', zh: '路由器', explain: 'a network traffic director' },
            { en: 'scalable', zh: '可扩展的', explain: 'able to grow in capacity' },
            { en: 'server', zh: '服务器', explain: 'a computer providing services' },
            { en: 'software', zh: '软件', explain: 'computer programs' },
            { en: 'spam', zh: '垃圾邮件', explain: 'unsolicited bulk messages' },
            { en: 'storage', zh: '存储', explain: 'a place to keep data' },
            { en: 'streaming', zh: '流媒体', explain: 'transmitting data in real-time' },
            { en: 'synchronize', zh: '同步', explain: 'to make match in time' },
            { en: 'syntax', zh: '语法；句法', explain: 'the rules of language structure' },
            { en: 'throughput', zh: '吞吐量', explain: 'the amount of data processed' },
            { en: 'upload', zh: '上传', explain: 'to transfer data to a server' },
            { en: 'virtual', zh: '虚拟的', explain: 'simulated by a computer' },
            { en: 'vulnerability', zh: '漏洞；脆弱性', explain: 'a weakness in security' },
            { en: 'widget', zh: '小部件', explain: 'a small application or tool' },
        ]
    }
};

// 将扩展词库合并到 WORD_LIBRARIES，并重建 WORDS_DATA
(function () {
    for (const key of Object.keys(WORD_LIBRARIES_EXTENDED)) {
        if (!WORD_LIBRARIES[key]) {
            WORD_LIBRARIES[key] = WORD_LIBRARIES_EXTENDED[key];
        }
    }
    // 重算总词数供显示
    let total = 0;
    for (const key of Object.keys(WORD_LIBRARIES)) {
        total += WORD_LIBRARIES[key].data.length;
    }
    window._TOTAL_WORDS = total;
})();
